export enum Jurusan {
  Matematika = "Matematika",
  Fisika = "Fisika",
  Astronomi = "Astronomi",
  Mikrobiologi = "Mikrobiologi",
  Kimia = "Kimia",
  Biologi = "Biologi",
  SainsDanTeknologiFarmasi = "Sains dan Teknologi Farmasi",
  Aktuaria = "Aktuaria",
  RekayasaHayati = "Rekayasa Hayati",
  RekayasaPertanian = "Rekayasa Pertanian",
  RekayasaKehutanan = "Rekayasa Kehutanan",
  FarmasiKlinikDanKomunitas = "Farmasi Klinik dan Komunitas",
  TeknologiPascaPanen = "Teknologi Pasca Panen",
  TeknikGeologi = "Teknik Geologi",
  TeknikPertambangan = "Teknik Pertambangan",
  TeknikPerminyakan = "Teknik Perminyakan",
  TeknikGeofisika = "Teknik Geofisika",
  TeknikMetalurgi = "Teknik Metalurgi",
  Meteorologi = "Meteorologi",
  Oseanografi = "Oseanografi",
  TeknikKimia = "Teknik Kimia",
  TeknikMesin = "Teknik Mesin",
  TeknikElektro = "Teknik Elektro",
  TeknikFisika = "Teknik Fisika",
  TeknikIndustri = "Teknik Industri",
  TeknikInformatika = "Teknik Informatika",
  AeronotikaDanAstronotika = "Aeronotika dan Astronotika",
  TeknikMaterial = "Teknik Material",
  TeknikPangan = "Teknik Pangan",
  ManajemenRekayasaIndustri = "Manajemen Rekayasa Industri",
  TeknikBioenergiDanKemurgi = "Teknik Bioenergi dan Kemurgi",
  TeknikSipil = "Teknik Sipil",
  TeknikGeodesiDanGeomatika = "Teknik Geodesi dan Geomatika",
  Arsitektur = "Arsitektur",
  TeknikLingkungan = "Teknik Lingkungan",
  PerencanaanWilayahDanKota = "Perencanaan Wilayah dan Kota",
  TeknikKelautan = "Teknik Kelautan",
  RekayasaInfrastrukturLingkungan = "Rekayasa Infrastruktur Lingkungan",
  TeknikDanPengelolaanSumberDayaAir = "Teknik dan Pengelolaan Sumber Daya Air",
  SeniRupa = "Seni Rupa",
  Desain = "Desain",
  Kriya = "Kriya",
  DesainInterior = "Desain Interior",
  DesainKomunikasiVisual = "Desain Komunikasi Visual",
  DesainProduk = "Desain Produk",
  TeknikTenagaListrik = "Teknik Tenaga Listrik",
  TeknikTelekomunikasi = "Teknik Telekomunikasi",
  SistemTeknologiDanInformasi = "Sistem Teknologi dan Informasi",
  TeknikBiomedis = "Teknik Biomedis",
  Manajemen = "Manajemen",
  Kewirausahaan = "Kewirausahaan",
}

export enum Fakultas {
  FMIPA = "FMIPA",
  SITHS = "SITH-S",
  SF = "SF",
  FITB = "FITB",
  FTTM = "FTTM",
  STEIR = "STEI-R",
  FTSL = "FTSL",
  FTI = "FTI",
  FSRD = "FSRD",
  FTMD = "FTMD",
  STEIK = "STEI-K",
  SBM = "SBM",
  SITHR = "SITH-R",
  SAPPK = "SAPPK",
}

export function getNimJurusanCodeMap(): Record<string, Jurusan> {
  return {
    "101": Jurusan.Matematika,
    "102": Jurusan.Fisika,
    "103": Jurusan.Astronomi,
    "104": Jurusan.Mikrobiologi,
    "105": Jurusan.Kimia,
    "106": Jurusan.Biologi,
    "107": Jurusan.SainsDanTeknologiFarmasi,
    "108": Jurusan.Aktuaria,
    "112": Jurusan.RekayasaHayati,
    "114": Jurusan.RekayasaPertanian,
    "115": Jurusan.RekayasaKehutanan,
    "116": Jurusan.FarmasiKlinikDanKomunitas,
    "119": Jurusan.TeknologiPascaPanen,
    "120": Jurusan.TeknikGeologi,
    "121": Jurusan.TeknikPertambangan,
    "122": Jurusan.TeknikPerminyakan,
    "123": Jurusan.TeknikGeofisika,
    "125": Jurusan.TeknikMetalurgi,
    "128": Jurusan.Meteorologi,
    "129": Jurusan.Oseanografi,
    "130": Jurusan.TeknikKimia,
    "131": Jurusan.TeknikMesin,
    "132": Jurusan.TeknikElektro,
    "133": Jurusan.TeknikFisika,
    "134": Jurusan.TeknikIndustri,
    "135": Jurusan.TeknikInformatika,
    "136": Jurusan.AeronotikaDanAstronotika,
    "137": Jurusan.TeknikMaterial,
    "143": Jurusan.TeknikPangan,
    "144": Jurusan.ManajemenRekayasaIndustri,
    "145": Jurusan.TeknikBioenergiDanKemurgi,
    "150": Jurusan.TeknikSipil,
    "151": Jurusan.TeknikGeodesiDanGeomatika,
    "152": Jurusan.Arsitektur,
    "153": Jurusan.TeknikLingkungan,
    "154": Jurusan.PerencanaanWilayahDanKota,
    "155": Jurusan.TeknikKelautan,
    "157": Jurusan.RekayasaInfrastrukturLingkungan,
    "158": Jurusan.TeknikDanPengelolaanSumberDayaAir,
    "170": Jurusan.SeniRupa,
    "171": Jurusan.Desain,
    "172": Jurusan.Kriya,
    "173": Jurusan.DesainInterior,
    "174": Jurusan.DesainKomunikasiVisual,
    "175": Jurusan.DesainProduk,
    "180": Jurusan.TeknikTenagaListrik,
    "181": Jurusan.TeknikTelekomunikasi,
    "182": Jurusan.SistemTeknologiDanInformasi,
    "183": Jurusan.TeknikBiomedis,
    "190": Jurusan.Manajemen,
    "192": Jurusan.Kewirausahaan,
  };
}

export function getNimFakultasCodeMap(): Record<string, Fakultas> {
  return {
    "160": Fakultas.FMIPA,
    "161": Fakultas.SITHS,
    "162": Fakultas.SF,
    "163": Fakultas.FITB,
    "164": Fakultas.FTTM,
    "165": Fakultas.STEIR,
    "166": Fakultas.FTSL,
    "167": Fakultas.FTI,
    "168": Fakultas.FSRD,
    "169": Fakultas.FTMD,
    "196": Fakultas.STEIK,
    "197": Fakultas.SBM,
    "198": Fakultas.SITHR,
    "199": Fakultas.SAPPK,
  };
}

export function getNimFakultasFromNimJurusanMap(): Record<string, string> {
  return {
    "101": "160",
    "102": "160",
    "103": "160",
    "104": "160",
    "105": "160",
    "106": "161",
    "107": "162",
    "108": "160",
    "112": "198",
    "114": "198",
    "115": "198",
    "116": "162",
    "119": "198",
    "120": "163",
    "121": "164",
    "122": "164",
    "123": "164",
    "125": "164",
    "128": "163",
    "129": "163",
    "130": "167",
    "131": "169",
    "132": "165",
    "133": "167",
    "134": "167",
    "135": "196",
    "136": "169",
    "137": "169",
    "143": "167",
    "144": "167",
    "145": "167",
    "150": "166",
    "151": "163",
    "152": "199",
    "153": "166",
    "154": "199",
    "155": "166",
    "157": "166",
    "158": "166",
    "170": "168",
    "171": "168",
    "172": "168",
    "173": "168",
    "174": "168",
    "175": "168",
    "180": "165",
    "181": "165",
    "182": "196",
    "183": "165",
    "190": "197",
    "192": "197",
  };
}

export function censorNim(nim: string): string {
  return `${nim.slice(0, 5)}XXX`;
}

export const majors = [
  { value: "Matematika", label: "Matematika" },
  { value: "Fisika", label: "Fisika" },
  { value: "Astronomi", label: "Astronomi" },
  { value: "Mikrobiologi", label: "Mikrobiologi" },
  { value: "Kimia", label: "Kimia" },
  { value: "Biologi", label: "Biologi" },
  {
    value: "Sains dan Teknologi Farmasi",
    label: "Sains dan Teknologi Farmasi",
  },
  { value: "Aktuaria", label: "Aktuaria" },
  { value: "Rekayasa Hayati", label: "Rekayasa Hayati" },
  { value: "Rekayasa Pertanian", label: "Rekayasa Pertanian" },
  { value: "Rekayasa Kehutanan", label: "Rekayasa Kehutanan" },
  {
    value: "Farmasi Klinik dan Komunitas",
    label: "Farmasi Klinik dan Komunitas",
  },
  { value: "Teknologi Pasca Panen", label: "Teknologi Pasca Panen" },
  { value: "Teknik Geologi", label: "Teknik Geologi" },
  { value: "Teknik Pertambangan", label: "Teknik Pertambangan" },
  { value: "Teknik Perminyakan", label: "Teknik Perminyakan" },
  { value: "Teknik Geofisika", label: "Teknik Geofisika" },
  { value: "Teknik Metalurgi", label: "Teknik Metalurgi" },
  { value: "Meteorologi", label: "Meteorologi" },
  { value: "Oseanografi", label: "Oseanografi" },
  { value: "Teknik Kimia", label: "Teknik Kimia" },
  { value: "Teknik Mesin", label: "Teknik Mesin" },
  { value: "Teknik Elektro", label: "Teknik Elektro" },
  { value: "Teknik Fisika", label: "Teknik Fisika" },
  { value: "Teknik Industri", label: "Teknik Industri" },
  { value: "Teknik Informatika", label: "Teknik Informatika" },
  { value: "Aeronotika dan Astronotika", label: "Aeronotika dan Astronotika" },
  { value: "Teknik Material", label: "Teknik Material" },
  { value: "Teknik Pangan", label: "Teknik Pangan" },
  {
    value: "Manajemen Rekayasa Industri",
    label: "Manajemen Rekayasa Industri",
  },
  {
    value: "Teknik Bioenergi dan Kemurgi",
    label: "Teknik Bioenergi dan Kemurgi",
  },
  { value: "Teknik Sipil", label: "Teknik Sipil" },
  {
    value: "Teknik Geodesi dan Geomatika",
    label: "Teknik Geodesi dan Geomatika",
  },
  { value: "Arsitektur", label: "Arsitektur" },
  { value: "Teknik Lingkungan", label: "Teknik Lingkungan" },
  {
    value: "Perencanaan Wilayah dan Kota",
    label: "Perencanaan Wilayah dan Kota",
  },
  { value: "Teknik Kelautan", label: "Teknik Kelautan" },
  {
    value: "Rekayasa Infrastruktur Lingkungan",
    label: "Rekayasa Infrastruktur Lingkungan",
  },
  {
    value: "Teknik dan Pengelolaan Sumber Daya Air",
    label: "Teknik dan Pengelolaan Sumber Daya Air",
  },
  { value: "Seni Rupa", label: "Seni Rupa" },
  { value: "Desain", label: "Desain" },
  { value: "Kriya", label: "Kriya" },
  { value: "Desain Interior", label: "Desain Interior" },
  { value: "Desain Komunikasi Visual", label: "Desain Komunikasi Visual" },
  { value: "Desain Produk", label: "Desain Produk" },
  { value: "Teknik Tenaga Listrik", label: "Teknik Tenaga Listrik" },
  { value: "Teknik Telekomunikasi", label: "Teknik Telekomunikasi" },
  {
    value: "Sistem Teknologi dan Informasi",
    label: "Sistem Teknologi dan Informasi",
  },
  { value: "Teknik Biomedis", label: "Teknik Biomedis" },
  { value: "Manajemen", label: "Manajemen" },
  { value: "Kewirausahaan", label: "Kewirausahaan" },
];

export const faculties = [
  { value: "FMIPA", label: "FMIPA" },
  { value: "SITH-S", label: "SITH-S" },
  { value: "SF", label: "SF" },
  { value: "FITB", label: "FITB" },
  { value: "FTTM", label: "FTTM" },
  { value: "STEI-R", label: "STEI-R" },
  { value: "FTSL", label: "FTSL" },
  { value: "FTI", label: "FTI" },
  { value: "FSRD", label: "FSRD" },
  { value: "FTMD", label: "FTMD" },
  { value: "STEI-K", label: "STEI-K" },
  { value: "SBM", label: "SBM" },
  { value: "SITH-R", label: "SITH-R" },
  { value: "SAPPK", label: "SAPPK" },
];
