server {
    listen 3000;
    server_name _;

    location /ota/ {
        alias /usr/share/nginx/html/ota/;
        try_files $uri $uri/ /ota/index.html;
    }

    location = / {
        return 301 /ota/;
    }
}
