FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY schema.prisma ./

RUN npm ci --quiet

CMD ["sh", "-c", "npx prisma db push --skip-generate --accept-data-loss && echo 'Schema ready'"]
