import { hash } from "bcrypt";
import { addMonths, setDate } from "date-fns";
import { v4 as uuidv4 } from "uuid";

import { db } from "../drizzle.js";
import {
  accountAdminDetailTable,
  accountMahasiswaDetailTable,
  accountOtaDetailTable,
  accountTable,
  connectionTable,
  transactionTable,
} from "../schema.js";

export async function seed() {
  try {
    console.log("Starting database seeding...");

    const hashedPassword = await hash("Password123!", 10);

    // Generate UUIDs
    const adminId = uuidv4();
    const bankes1Id = uuidv4();
    const bankes2Id = uuidv4();
    const pengurus1Id = uuidv4();
    const pengurus2Id = uuidv4();
    const mahasiswa1Id = uuidv4();
    const mahasiswa2Id = uuidv4();
    const mahasiswa3Id = uuidv4();
    const mahasiswa4Id = uuidv4();
    const mahasiswa5Id = uuidv4();
    const mahasiswa6Id = uuidv4();
    const mahasiswa7Id = uuidv4();
    const mahasiswa8Id = uuidv4();
    const mahasiswa9Id = uuidv4();
    const mahasiswa10Id = uuidv4();
    const mahasiswa11Id = uuidv4();
    const mahasiswa12Id = uuidv4();
    const mahasiswa13Id = uuidv4();
    const mahasiswa14Id = uuidv4();
    const mahasiswa15Id = uuidv4();
    const mahasiswa16Id = uuidv4();
    const mahasiswa17Id = uuidv4();
    const mahasiswa18Id = uuidv4();
    const ota1Id = uuidv4();
    const ota2Id = uuidv4();
    const ota3Id = uuidv4();
    const ota4Id = uuidv4();
    const ota5Id = uuidv4();
    const ota6Id = uuidv4();
    const ota7Id = uuidv4();
    const ota8Id = uuidv4();
    const ota9Id = uuidv4();
    const ota10Id = uuidv4();
    const ota11Id = uuidv4();
    const ota12Id = uuidv4();
    const ota13Id = uuidv4();
    const ota14Id = uuidv4();
    const ota15Id = uuidv4();

    const currentDateTime = new Date();
    // Due date time is 6 months from now
    const dueDateTime = new Date(
      currentDateTime.getFullYear(),
      currentDateTime.getMonth() + 6,
      currentDateTime.getDate(),
      currentDateTime.getHours(),
      currentDateTime.getMinutes(),
      currentDateTime.getSeconds(),
      currentDateTime.getMilliseconds(),
    );

    await db.transaction(async (tx) => {
      await tx
        .insert(accountTable)
        .values([
          {
            id: adminId,
            email: "admin@example.com",
            phoneNumber: "628123456789",
            password: hashedPassword,
            type: "admin",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: bankes1Id,
            email: "bankes1@example.com",
            phoneNumber: "628121865489",
            password: hashedPassword,
            type: "bankes",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: bankes2Id,
            email: "bankes2@example.com",
            phoneNumber: "628129648526",
            password: hashedPassword,
            type: "bankes",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: pengurus1Id,
            email: "pengurus1@example.com",
            phoneNumber: "628127586245",
            password: hashedPassword,
            type: "pengurus",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: pengurus2Id,
            email: "pengurus2@example.com",
            phoneNumber: "628126548253",
            password: hashedPassword,
            type: "pengurus",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: mahasiswa1Id,
            email: "13599101@mahasiswa.itb.ac.id",
            phoneNumber: "628123456780",
            password: hashedPassword,
            type: "mahasiswa",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: mahasiswa2Id,
            email: "13299102@mahasiswa.itb.ac.id",
            phoneNumber: "628198765432",
            password: hashedPassword,
            type: "mahasiswa",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: mahasiswa3Id,
            email: "13199103@mahasiswa.itb.ac.id",
            phoneNumber: "628198702490",
            password: hashedPassword,
            type: "mahasiswa",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: mahasiswa4Id,
            email: "15099104@mahasiswa.itb.ac.id",
            phoneNumber: "628198766782",
            password: hashedPassword,
            type: "mahasiswa",
            status: "verified",
            applicationStatus: "pending",
          },
          {
            id: mahasiswa5Id,
            email: "13099105@mahasiswa.itb.ac.id",
            phoneNumber: "628198987411",
            password: hashedPassword,
            type: "mahasiswa",
            status: "verified",
            applicationStatus: "rejected",
          },
          {
            id: mahasiswa6Id,
            email: "15199106@mahasiswa.itb.ac.id",
            phoneNumber: "628100000006",
            password: hashedPassword,
            type: "mahasiswa",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: mahasiswa7Id,
            email: "12099107@mahasiswa.itb.ac.id",
            phoneNumber: "628100000007",
            password: hashedPassword,
            type: "mahasiswa",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: mahasiswa8Id,
            email: "15499108@mahasiswa.itb.ac.id",
            phoneNumber: "628100000008",
            password: hashedPassword,
            type: "mahasiswa",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: mahasiswa9Id,
            email: "15099109@mahasiswa.itb.ac.id",
            phoneNumber: "628100000009",
            password: hashedPassword,
            type: "mahasiswa",
            status: "verified",
            applicationStatus: "pending",
          },
          {
            id: mahasiswa10Id,
            email: "15499110@mahasiswa.itb.ac.id",
            phoneNumber: "628100000010",
            password: hashedPassword,
            type: "mahasiswa",
            status: "verified",
            applicationStatus: "pending",
          },
          {
            id: mahasiswa11Id,
            email: "13499111@mahasiswa.itb.ac.id",
            phoneNumber: "628100000011",
            password: hashedPassword,
            type: "mahasiswa",
            status: "verified",
            applicationStatus: "rejected",
          },
          {
            id: mahasiswa12Id,
            email: "13199112@mahasiswa.itb.ac.id",
            phoneNumber: "628100000012",
            password: hashedPassword,
            type: "mahasiswa",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: mahasiswa13Id,
            email: "13099113@mahasiswa.itb.ac.id",
            phoneNumber: "628100000013",
            password: hashedPassword,
            type: "mahasiswa",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: mahasiswa14Id,
            email: "10199114@mahasiswa.itb.ac.id",
            phoneNumber: "628100000014",
            password: hashedPassword,
            type: "mahasiswa",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: mahasiswa15Id,
            email: "15299115@mahasiswa.itb.ac.id",
            phoneNumber: "628100000015",
            password: hashedPassword,
            type: "mahasiswa",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: mahasiswa16Id,
            email: "19099116@mahasiswa.itb.ac.id",
            phoneNumber: "628100000016",
            password: hashedPassword,
            type: "mahasiswa",
            status: "verified",
            applicationStatus: "pending",
          },
          {
            id: mahasiswa17Id,
            email: "10399117@mahasiswa.itb.ac.id",
            phoneNumber: "628100000017",
            password: hashedPassword,
            type: "mahasiswa",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: mahasiswa18Id,
            email: "13599118@mahasiswa.itb.ac.id",
            phoneNumber: "628100000018",
            password: hashedPassword,
            type: "mahasiswa",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: ota1Id,
            email: "ota1@example.com",
            phoneNumber: "628111222333",
            password: hashedPassword,
            type: "ota",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: ota2Id,
            email: "ota2@example.com",
            phoneNumber: "628444555666",
            password: hashedPassword,
            type: "ota",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: ota3Id,
            email: "ota3@example.com",
            phoneNumber: "628111000003",
            password: hashedPassword,
            type: "ota",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: ota4Id,
            email: "ota4@example.com",
            phoneNumber: "628444000004",
            password: hashedPassword,
            type: "ota",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: ota5Id,
            email: "ota5@example.com",
            phoneNumber: "628111000005",
            password: hashedPassword,
            type: "ota",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: ota6Id,
            email: "ota6@example.com",
            phoneNumber: "628444000006",
            password: hashedPassword,
            type: "ota",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: ota7Id,
            email: "ota7@example.com",
            phoneNumber: "628111000007",
            password: hashedPassword,
            type: "ota",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: ota8Id,
            email: "ota8@example.com",
            phoneNumber: "628444000008",
            password: hashedPassword,
            type: "ota",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: ota9Id,
            email: "ota9@example.com",
            phoneNumber: "628444000009",
            password: hashedPassword,
            type: "ota",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: ota10Id,
            email: "ota10@example.com",
            phoneNumber: "628444000010",
            password: hashedPassword,
            type: "ota",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: ota11Id,
            email: "ota11@example.com",
            phoneNumber: "628444000011",
            password: hashedPassword,
            type: "ota",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: ota12Id,
            email: "ota12@example.com",
            phoneNumber: "628444000012",
            password: hashedPassword,
            type: "ota",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: ota13Id,
            email: "ota13@example.com",
            phoneNumber: "628444000013",
            password: hashedPassword,
            type: "ota",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: ota14Id,
            email: "ota14@example.com",
            phoneNumber: "628444000014",
            password: hashedPassword,
            type: "ota",
            status: "verified",
            applicationStatus: "accepted",
          },
          {
            id: ota15Id,
            email: "ota15@example.com",
            phoneNumber: "628444000015",
            password: hashedPassword,
            type: "ota",
            status: "verified",
            applicationStatus: "accepted",
          },
        ])
        .onConflictDoNothing();

      console.log("Account tables seeded");
    });

    await db.transaction(async (tx) => {
      await tx
        .insert(accountMahasiswaDetailTable)
        .values([
          {
            accountId: mahasiswa1Id,
            name: "Mahasiswa One",
            nim: "13599101",
            description: "Mahasiswa One is an active student.",
            file: "https://example.com/mahasiswa1.pdf",
            mahasiswaStatus: "active",
            major: "Teknik Informatika",
            faculty: "STEI-K",
            cityOfOrigin: "Jakarta",
            highschoolAlumni: "SMA Negeri 1 Jakarta",
            kk: "https://example.com/kk1.pdf",
            ktm: "https://example.com/ktm1.pdf",
            waliRecommendationLetter: "https://example.com/wali1.pdf",
            transcript: "https://example.com/transcript1.pdf",
            salaryReport: "https://example.com/salary1.pdf",
            pbb: "https://example.com/pbb1.pdf",
            electricityBill: "https://example.com/electricity1.pdf",
            ditmawaRecommendationLetter: "https://example.com/ditmawa1.pdf",
            notes: "Mahasiswa muslim with GPA 3.8",
            adminOnlyNotes: "Mahasiswa has a scholarship from the government",
            createdAt: currentDateTime,
            updatedAt: currentDateTime,
            dueNextUpdateAt: dueDateTime,
            gender: "M",
            religion: "Islam",
            gpa: "3.8",
            bill: 250000,
          },
          {
            accountId: mahasiswa2Id,
            name: "Mahasiswa Two",
            nim: "13299102",
            description: "Mahasiswa Two is an active student.",
            file: "https://example.com/mahasiswa2.pdf",
            mahasiswaStatus: "active",
            major: "Teknik Elektro",
            faculty: "STEI-R",
            cityOfOrigin: "Bandung",
            highschoolAlumni: "SMA Negeri 2 Bandung",
            kk: "https://example.com/kk2.pdf",
            ktm: "https://example.com/ktm2.pdf",
            waliRecommendationLetter: "https://example.com/wali2.pdf",
            transcript: "https://example.com/transcript2.pdf",
            salaryReport: "https://example.com/salary2.pdf",
            pbb: "https://example.com/pbb2.pdf",
            electricityBill: "https://example.com/electricity2.pdf",
            ditmawaRecommendationLetter: "https://example.com/ditmawa2.pdf",
            notes: "Mahasiswa non-muslim with GPA 3.5",
            adminOnlyNotes: "Mahasiswa has a scholarship from the university",
            createdAt: currentDateTime,
            updatedAt: currentDateTime,
            dueNextUpdateAt: dueDateTime,
            gender: "F",
            religion: "Kristen Protestan",
            gpa: "3.5",
            bill: 250000,
          },
          {
            accountId: mahasiswa3Id,
            name: "Mahasiswa Three",
            nim: "13199103",
            description: "Mahasiswa Three is an active student.",
            file: "https://example.com/mahasiswa3.pdf",
            mahasiswaStatus: "active",
            major: "Teknik Mesin",
            faculty: "FTMD",
            cityOfOrigin: "Surabaya",
            highschoolAlumni: "SMA Negeri 3 Surabaya",
            kk: "https://example.com/kk3.pdf",
            ktm: "https://example.com/ktm3.pdf",
            waliRecommendationLetter: "https://example.com/wali3.pdf",
            transcript: "https://example.com/transcript3.pdf",
            salaryReport: "https://example.com/salary3.pdf",
            pbb: "https://example.com/pbb3.pdf",
            electricityBill: "https://example.com/electricity3.pdf",
            ditmawaRecommendationLetter: "https://example.com/ditmawa3.pdf",
            notes: "Mahasiswa muslim with GPA 3.9",
            adminOnlyNotes: "Mahasiswa has a scholarship from the government",
            createdAt: currentDateTime,
            updatedAt: currentDateTime,
            dueNextUpdateAt: dueDateTime,
            gender: "M",
            religion: "Islam",
            gpa: "3.9",
            bill: 400000,
          },
          {
            accountId: mahasiswa4Id,
            name: "Mahasiswa Four",
            nim: "15099104",
            description: "Mahasiswa Four is an inactive student.",
            file: "https://example.com/mahasiswa4.pdf",
            mahasiswaStatus: "inactive",
            major: "Teknik Sipil",
            faculty: "FTSL",
            cityOfOrigin: "Yogyakarta",
            highschoolAlumni: "SMA Negeri 4 Yogyakarta",
            kk: "https://example.com/kk4.pdf",
            ktm: "https://example.com/ktm4.pdf",
            waliRecommendationLetter: "https://example.com/wali4.pdf",
            transcript: "https://example.com/transcript4.pdf",
            salaryReport: "https://example.com/salary4.pdf",
            pbb: "https://example.com/pbb4.pdf",
            electricityBill: "https://example.com/electricity4.pdf",
            createdAt: currentDateTime,
            updatedAt: currentDateTime,
            dueNextUpdateAt: dueDateTime,
            religion: "Hindu",
            gpa: "3.2",
            gender: "F",
          },
          {
            accountId: mahasiswa5Id,
            name: "Mahasiswa Five",
            nim: "13099105",
            description: "Mahasiswa Five is an inactive student.",
            file: "https://example.com/mahasiswa5.pdf",
            mahasiswaStatus: "inactive",
            major: "Teknik Kimia",
            faculty: "FTI",
            cityOfOrigin: "Medan",
            highschoolAlumni: "SMA Negeri 5 Medan",
            kk: "https://example.com/kk5.pdf",
            ktm: "https://example.com/ktm5.pdf",
            waliRecommendationLetter: "https://example.com/wali5.pdf",
            transcript: "https://example.com/transcript5.pdf",
            salaryReport: "https://example.com/salary5.pdf",
            pbb: "https://example.com/pbb5.pdf",
            electricityBill: "https://example.com/electricity5.pdf",
            ditmawaRecommendationLetter: "https://example.com/ditmawa5.pdf",
            notes: "Rejected because of not a good student",
            adminOnlyNotes: "Mahasiswa had fight with other students",
            createdAt: currentDateTime,
            updatedAt: currentDateTime,
            dueNextUpdateAt: dueDateTime,
            gender: "M",
            religion: "Islam",
            gpa: "2.5",
          },
          {
            accountId: mahasiswa6Id,
            name: "Mahasiswa Six",
            nim: "15199106",
            description: "Mahasiswa Six is an active student.",
            file: "https://example.com/mahasiswa6.pdf",
            mahasiswaStatus: "inactive",
            major: "Teknik Geodesi dan Geomatika",
            faculty: "FITB",
            cityOfOrigin: "Makassar",
            highschoolAlumni: "SMA Negeri 6 Makassar",
            kk: "https://example.com/kk6.pdf",
            ktm: "https://example.com/ktm6.pdf",
            waliRecommendationLetter: "https://example.com/wali6.pdf",
            transcript: "https://example.com/transcript6.pdf",
            salaryReport: "https://example.com/salary6.pdf",
            pbb: "https://example.com/pbb6.pdf",
            electricityBill: "https://example.com/electricity6.pdf",
            ditmawaRecommendationLetter: "https://example.com/ditmawa6.pdf",
            notes: "Actively involved in student organizations.",
            adminOnlyNotes: "Potential candidate for OTA2",
            createdAt: currentDateTime,
            updatedAt: currentDateTime,
            dueNextUpdateAt: dueDateTime,
            gender: "F",
            religion: "Katolik",
            gpa: "3.7",
            bill: 500000,
          },
          {
            accountId: mahasiswa7Id,
            name: "Mahasiswa Seven",
            nim: "12099107",
            description: "Mahasiswa Seven is an active student.",
            file: "https://example.com/mahasiswa7.pdf",
            mahasiswaStatus: "inactive",
            major: "Teknik Geologi",
            faculty: "FITB",
            cityOfOrigin: "Palembang",
            highschoolAlumni: "SMA Negeri 7 Palembang",
            kk: "https://example.com/kk7.pdf",
            ktm: "https://example.com/ktm7.pdf",
            waliRecommendationLetter: "https://example.com/wali7.pdf",
            transcript: "https://example.com/transcript7.pdf",
            salaryReport: "https://example.com/salary7.pdf",
            pbb: "https://example.com/pbb7.pdf",
            electricityBill: "https://example.com/electricity7.pdf",
            ditmawaRecommendationLetter: "https://example.com/ditmawa7.pdf",
            notes: "Has strong academic performance.",
            adminOnlyNotes: "Recommend for follow-up interview.",
            createdAt: currentDateTime,
            updatedAt: currentDateTime,
            dueNextUpdateAt: dueDateTime,
            gender: "M",
            religion: "Islam",
            gpa: "3.6",
            bill: 200000,
          },
          {
            accountId: mahasiswa8Id,
            name: "Mahasiswa Eight",
            nim: "15499108",
            description: "Mahasiswa Eight is an active student.",
            file: "https://example.com/mahasiswa8.pdf",
            mahasiswaStatus: "inactive",
            major: "Perencanaan Wilayah dan Kota",
            faculty: "SAPPK",
            cityOfOrigin: "Denpasar",
            highschoolAlumni: "SMA Negeri 8 Denpasar",
            kk: "https://example.com/kk8.pdf",
            ktm: "https://example.com/ktm8.pdf",
            waliRecommendationLetter: "https://example.com/wali8.pdf",
            transcript: "https://example.com/transcript8.pdf",
            salaryReport: "https://example.com/salary8.pdf",
            pbb: "https://example.com/pbb8.pdf",
            electricityBill: "https://example.com/electricity8.pdf",
            ditmawaRecommendationLetter: "https://example.com/ditmawa8.pdf",
            notes: "Very active in environmental campaigns.",
            adminOnlyNotes: "Low income family background.",
            createdAt: currentDateTime,
            updatedAt: currentDateTime,
            dueNextUpdateAt: dueDateTime,
            gender: "F",
            religion: "Hindu",
            gpa: "3.8",
            bill: 200000,
          },
          {
            accountId: mahasiswa9Id,
            name: "Mahasiswa Nine",
            nim: "15099109",
            description: "Mahasiswa Nine is an active student.",
            file: "https://example.com/mahasiswa9.pdf",
            mahasiswaStatus: "active",
            major: "Teknik Sipil",
            faculty: "FTSL",
            cityOfOrigin: "Surabaya",
            highschoolAlumni: "SMA Negeri 9 Surabaya",
            kk: "https://example.com/kk9.pdf",
            ktm: "https://example.com/ktm9.pdf",
            waliRecommendationLetter: "https://example.com/wali9.pdf",
            transcript: "https://example.com/transcript9.pdf",
            salaryReport: "https://example.com/salary9.pdf",
            pbb: "https://example.com/pbb9.pdf",
            electricityBill: "https://example.com/electricity9.pdf",
            ditmawaRecommendationLetter: "https://example.com/ditmawa9.pdf",
            createdAt: currentDateTime,
            updatedAt: currentDateTime,
            dueNextUpdateAt: dueDateTime,
            gender: "M",
            religion: "Islam",
            gpa: "3.5",
          },
          {
            accountId: mahasiswa10Id,
            name: "Mahasiswa Ten",
            nim: "15499110",
            description: "Mahasiswa Ten is an active student.",
            file: "https://example.com/mahasiswa10.pdf",
            mahasiswaStatus: "inactive",
            major: "Perencanaan Wilayah dan Kota",
            faculty: "SAPPK",
            cityOfOrigin: "Bandar Lampung",
            highschoolAlumni: "SMA Negeri 10 Bandar Lampung",
            kk: "https://example.com/kk10.pdf",
            ktm: "https://example.com/ktm10.pdf",
            waliRecommendationLetter: "https://example.com/wali10.pdf",
            transcript: "https://example.com/transcript10.pdf",
            salaryReport: "https://example.com/salary10.pdf",
            pbb: "https://example.com/pbb10.pdf",
            electricityBill: "https://example.com/electricity10.pdf",
            ditmawaRecommendationLetter: "https://example.com/ditmawa10.pdf",
            createdAt: currentDateTime,
            updatedAt: currentDateTime,
            dueNextUpdateAt: dueDateTime,
            gender: "F",
            religion: "Hindu",
            gpa: "3.9",
          },
          {
            accountId: mahasiswa11Id,
            name: "Mahasiswa Eleven",
            nim: "13499111",
            description: "Mahasiswa Eleven is an active student.",
            file: "https://example.com/mahasiswa11.pdf",
            mahasiswaStatus: "inactive",
            major: "Teknik Industri",
            faculty: "FTI",
            cityOfOrigin: "Pekanbaru",
            highschoolAlumni: "SMA Negeri 11 Pekanbaru",
            kk: "https://example.com/kk11.pdf",
            ktm: "https://example.com/ktm11.pdf",
            waliRecommendationLetter: "https://example.com/wali11.pdf",
            transcript: "https://example.com/transcript11.pdf",
            salaryReport: "https://example.com/salary11.pdf",
            pbb: "https://example.com/pbb11.pdf",
            electricityBill: "https://example.com/electricity11.pdf",
            ditmawaRecommendationLetter: "https://example.com/ditmawa11.pdf",
            notes: "Organized student-led career fair.",
            adminOnlyNotes: "Interest in internship support program.",
            createdAt: currentDateTime,
            updatedAt: currentDateTime,
            dueNextUpdateAt: dueDateTime,
            gender: "F",
            religion: "Hindu",
            gpa: "3.6",
          },
          {
            accountId: mahasiswa12Id,
            name: "Mahasiswa Twelve",
            nim: "13199112",
            description: "Mahasiswa Twelve is an active student.",
            file: "https://example.com/mahasiswa12.pdf",
            mahasiswaStatus: "inactive",
            major: "Teknik Mesin",
            faculty: "FTMD",
            cityOfOrigin: "Pontianak",
            highschoolAlumni: "SMA Negeri 12 Pontianak",
            kk: "https://example.com/kk12.pdf",
            ktm: "https://example.com/ktm12.pdf",
            waliRecommendationLetter: "https://example.com/wali12.pdf",
            transcript: "https://example.com/transcript12.pdf",
            salaryReport: "https://example.com/salary12.pdf",
            pbb: "https://example.com/pbb12.pdf",
            electricityBill: "https://example.com/electricity12.pdf",
            ditmawaRecommendationLetter: "https://example.com/ditmawa12.pdf",
            notes: "Builds robots for national competition.",
            adminOnlyNotes: "Strong technical profile.",
            createdAt: currentDateTime,
            updatedAt: currentDateTime,
            dueNextUpdateAt: dueDateTime,
            gender: "M",
            religion: "Buddha",
            gpa: "3.7",
            bill: 400000,
          },
          {
            accountId: mahasiswa13Id,
            name: "Mahasiswa Thirteen",
            nim: "13099113",
            description: "Mahasiswa Thirteen is an active student.",
            file: "https://example.com/mahasiswa13.pdf",
            mahasiswaStatus: "inactive",
            major: "Teknik Kimia",
            faculty: "FTI",
            cityOfOrigin: "Manado",
            highschoolAlumni: "SMA Negeri 13 Manado",
            kk: "https://example.com/kk13.pdf",
            ktm: "https://example.com/ktm13.pdf",
            waliRecommendationLetter: "https://example.com/wali13.pdf",
            transcript: "https://example.com/transcript13.pdf",
            salaryReport: "https://example.com/salary13.pdf",
            pbb: "https://example.com/pbb13.pdf",
            electricityBill: "https://example.com/electricity13.pdf",
            ditmawaRecommendationLetter: "https://example.com/ditmawa13.pdf",
            notes: "Works part-time as chemistry tutor.",
            adminOnlyNotes: "Time management skill noted.",
            createdAt: currentDateTime,
            updatedAt: currentDateTime,
            dueNextUpdateAt: dueDateTime,
            gender: "F",
            religion: "Kristen Protestan",
            gpa: "3.5",
            bill: 500000,
          },
          {
            accountId: mahasiswa14Id,
            name: "Mahasiswa Fourteen",
            nim: "10199114",
            description: "Mahasiswa Fourteen is an active student.",
            file: "https://example.com/mahasiswa14.pdf",
            mahasiswaStatus: "inactive",
            major: "Matematika",
            faculty: "FMIPA",
            cityOfOrigin: "Cirebon",
            highschoolAlumni: "SMA Negeri 14 Cirebon",
            kk: "https://example.com/kk14.pdf",
            ktm: "https://example.com/ktm14.pdf",
            waliRecommendationLetter: "https://example.com/wali14.pdf",
            transcript: "https://example.com/transcript14.pdf",
            salaryReport: "https://example.com/salary14.pdf",
            pbb: "https://example.com/pbb14.pdf",
            electricityBill: "https://example.com/electricity14.pdf",
            ditmawaRecommendationLetter: "https://example.com/ditmawa14.pdf",
            notes: "Actively assists in math olympiad mentoring.",
            adminOnlyNotes: "Potential tutor for internal program.",
            createdAt: currentDateTime,
            updatedAt: currentDateTime,
            dueNextUpdateAt: dueDateTime,
            gender: "M",
            religion: "Islam",
            gpa: "3.9",
            bill: 200000,
          },
          {
            accountId: mahasiswa15Id,
            name: "Mahasiswa Fifteen",
            nim: "15299115",
            description: "Mahasiswa Fifteen is an active student.",
            file: "https://example.com/mahasiswa15.pdf",
            mahasiswaStatus: "inactive",
            major: "Arsitektur",
            faculty: "SAPPK",
            cityOfOrigin: "Yogyakarta",
            highschoolAlumni: "SMA Negeri 15 Yogyakarta",
            kk: "https://example.com/kk15.pdf",
            ktm: "https://example.com/ktm15.pdf",
            waliRecommendationLetter: "https://example.com/wali15.pdf",
            transcript: "https://example.com/transcript15.pdf",
            salaryReport: "https://example.com/salary15.pdf",
            pbb: "https://example.com/pbb15.pdf",
            electricityBill: "https://example.com/electricity15.pdf",
            ditmawaRecommendationLetter: "https://example.com/ditmawa15.pdf",
            notes: "Participated in regional architecture expo.",
            adminOnlyNotes: "Showcase potential project.",
            createdAt: currentDateTime,
            updatedAt: currentDateTime,
            dueNextUpdateAt: dueDateTime,
            gender: "F",
            religion: "Islam",
            gpa: "3.4",
            bill: 300000,
          },
          {
            accountId: mahasiswa16Id,
            name: "Mahasiswa Sixteen",
            nim: "19099116",
            description: "Mahasiswa Sixteen is an active student.",
            file: "https://example.com/mahasiswa16.pdf",
            mahasiswaStatus: "inactive",
            major: "Manajemen",
            faculty: "SBM",
            cityOfOrigin: "Mataram",
            highschoolAlumni: "SMA Negeri 16 Mataram",
            kk: "https://example.com/kk16.pdf",
            ktm: "https://example.com/ktm16.pdf",
            waliRecommendationLetter: "https://example.com/wali16.pdf",
            transcript: "https://example.com/transcript16.pdf",
            salaryReport: "https://example.com/salary16.pdf",
            pbb: "https://example.com/pbb16.pdf",
            electricityBill: "https://example.com/electricity16.pdf",
            ditmawaRecommendationLetter: "https://example.com/ditmawa16.pdf",
            createdAt: currentDateTime,
            updatedAt: currentDateTime,
            dueNextUpdateAt: dueDateTime,
            gender: "M",
            religion: "Islam",
            gpa: "3.8",
          },
          {
            accountId: mahasiswa17Id,
            name: "Mahasiswa Seventeen",
            nim: "10399117",
            description: "Mahasiswa Seventeen is an active student.",
            file: "https://example.com/mahasiswa17.pdf",
            mahasiswaStatus: "inactive",
            major: "Astronomi",
            faculty: "FMIPA",
            cityOfOrigin: "Ambon",
            highschoolAlumni: "SMA Negeri 17 Ambon",
            kk: "https://example.com/kk17.pdf",
            ktm: "https://example.com/ktm17.pdf",
            waliRecommendationLetter: "https://example.com/wali17.pdf",
            transcript: "https://example.com/transcript17.pdf",
            salaryReport: "https://example.com/salary17.pdf",
            pbb: "https://example.com/pbb17.pdf",
            electricityBill: "https://example.com/electricity17.pdf",
            ditmawaRecommendationLetter: "https://example.com/ditmawa17.pdf",
            notes: "Research assistant at Bosscha Observatory.",
            adminOnlyNotes: "May need transport stipend support.",
            createdAt: currentDateTime,
            updatedAt: currentDateTime,
            dueNextUpdateAt: dueDateTime,
            gender: "F",
            religion: "Katolik",
            gpa: "3.7",
            bill: 400000,
          },
          {
            accountId: mahasiswa18Id,
            name: "Mahasiswa Eighteen",
            nim: "13599118",
            description: "Mahasiswa Eighteen is an active student.",
            file: "https://example.com/mahasiswa18.pdf",
            mahasiswaStatus: "inactive",
            major: "Teknik Informatika",
            faculty: "STEI-K",
            cityOfOrigin: "Semarang",
            highschoolAlumni: "SMA Negeri 18 Semarang",
            kk: "https://example.com/kk18.pdf",
            ktm: "https://example.com/ktm18.pdf",
            waliRecommendationLetter: "https://example.com/wali18.pdf",
            transcript: "https://example.com/transcript18.pdf",
            salaryReport: "https://example.com/salary18.pdf",
            pbb: "https://example.com/pbb18.pdf",
            electricityBill: "https://example.com/electricity18.pdf",
            ditmawaRecommendationLetter: "https://example.com/ditmawa18.pdf",
            notes: "Built app to help visually impaired users.",
            adminOnlyNotes: "Candidate for tech scholarship.",
            createdAt: currentDateTime,
            updatedAt: currentDateTime,
            dueNextUpdateAt: dueDateTime,
            gender: "M",
            religion: "Islam",
            gpa: "3.95",
            bill: 500000,
          },
        ])
        .onConflictDoNothing();

      console.log("Mahasiswa details seeded");

      const otaDetails = await tx
        .insert(accountOtaDetailTable)
        .values([
          {
            accountId: ota1Id,
            name: "OTA Organization One",
            job: "Scholarship Provider",
            address: "Jl. Example No. 1, Jakarta",
            linkage: "otm",
            funds: 500000,
            maxCapacity: 3,
            startDate: new Date(),
            maxSemester: 8,
            transferDate: 10,
            criteria: "GPA minimum 3.5, active in organizations",
            isDetailVisible: true,
            allowAdminSelection: true,
          },
          {
            accountId: ota2Id,
            name: "OTA Organization Two",
            job: "Education Foundation",
            address: "Jl. Example No. 2, Bandung",
            linkage: "alumni",
            funds: 750000,
            maxCapacity: 2,
            startDate: new Date(),
            maxSemester: 6,
            transferDate: 15,
            criteria: "From underprivileged family, GPA minimum 3.0",
            isDetailVisible: true,
            allowAdminSelection: false,
          },
          {
            accountId: ota3Id,
            name: "Hope Foundation",
            job: "NGO",
            address: "Jl. Example No. 3, Jakarta",
            linkage: "otm",
            funds: 575000,
            maxCapacity: 3,
            startDate: new Date(),
            maxSemester: 7,
            transferDate: 6,
            criteria: "GPA minimum 3.0",
            isDetailVisible: true,
            allowAdminSelection: true,
          },
          {
            accountId: ota4Id,
            name: "Bright Future Org",
            job: "Private Donor",
            address: "Jl. Example No. 4, Bandung",
            linkage: "alumni",
            funds: 600000,
            maxCapacity: 4,
            startDate: new Date(),
            maxSemester: 8,
            transferDate: 7,
            criteria: "GPA 3.2 and above",
            allowAdminSelection: false,
            isDetailVisible: true,
          },
          {
            accountId: ota5Id,
            name: "SmartAid Indonesia",
            job: "Charity",
            address: "Jl. Example No. 5, Surabaya",
            linkage: "lainnya",
            funds: 625000,
            maxCapacity: 2,
            startDate: new Date(),
            maxSemester: 6,
            transferDate: 8,
            criteria: "Active in community service",
            isDetailVisible: true,
            allowAdminSelection: true,
          },
          {
            accountId: ota6Id,
            name: "Caring Hands",
            job: "Educational Institution",
            address: "Jl. Example No. 6, Yogyakarta",
            linkage: "otm",
            funds: 650000,
            maxCapacity: 3,
            startDate: new Date(),
            maxSemester: 7,
            transferDate: 9,
            criteria: "Low-income background",
            isDetailVisible: true,
            allowAdminSelection: false,
          },
          {
            accountId: ota7Id,
            name: "EduFunders",
            job: "Religious Organization",
            address: "Jl. Example No. 7, Semarang",
            linkage: "alumni",
            funds: 675000,
            maxCapacity: 4,
            startDate: new Date(),
            maxSemester: 8,
            transferDate: 10,
            criteria: "Eastern Indonesia origin",
            isDetailVisible: true,
            allowAdminSelection: true,
          },
          {
            accountId: ota8Id,
            name: "Light of Knowledge",
            job: "Tech Philanthropy",
            address: "Jl. Example No. 8, Medan",
            linkage: "lainnya",
            funds: 700000,
            maxCapacity: 2,
            startDate: new Date(),
            maxSemester: 6,
            transferDate: 11,
            criteria: "No active sanctions",
            isDetailVisible: true,
            allowAdminSelection: false,
          },
          {
            accountId: ota9Id,
            name: "Bakti Bangsa",
            job: "Social Enterprise",
            address: "Jl. Example No. 9, Makassar",
            linkage: "otm",
            funds: 725000,
            maxCapacity: 3,
            startDate: new Date(),
            maxSemester: 7,
            transferDate: 12,
            criteria: "Single parent household",
            isDetailVisible: false,
            allowAdminSelection: true,
          },
          {
            accountId: ota10Id,
            name: "Mentari Foundation",
            job: "Bank CSR",
            address: "Jl. Example No. 10, Padang",
            linkage: "alumni",
            funds: 750000,
            maxCapacity: 4,
            startDate: new Date(),
            maxSemester: 8,
            transferDate: 13,
            criteria: "Remote area student",
            isDetailVisible: false,
            allowAdminSelection: false,
          },
          {
            accountId: ota11Id,
            name: "Harapan Kita",
            job: "Startup Grantor",
            address: "Jl. Example No. 11, Palembang",
            linkage: "lainnya",
            funds: 775000,
            maxCapacity: 2,
            startDate: new Date(),
            maxSemester: 6,
            transferDate: 14,
            criteria: "First-generation college student",
            isDetailVisible: false,
            allowAdminSelection: true,
          },
          {
            accountId: ota12Id,
            name: "Generasi Cerdas",
            job: "Community Group",
            address: "Jl. Example No. 12, Denpasar",
            linkage: "otm",
            funds: 800000,
            maxCapacity: 3,
            startDate: new Date(),
            maxSemester: 7,
            transferDate: 15,
            criteria: "Participated in volunteer work",
            isDetailVisible: false,
            allowAdminSelection: false,
          },
          {
            accountId: ota13Id,
            name: "Pendidikan Untuk Semua",
            job: "Non-profit",
            address: "Jl. Example No. 13, Bogor",
            linkage: "alumni",
            funds: 825000,
            maxCapacity: 4,
            startDate: new Date(),
            maxSemester: 8,
            transferDate: 16,
            criteria: "STEM focus",
            isDetailVisible: false,
            allowAdminSelection: true,
          },
          {
            accountId: ota14Id,
            name: "Bumi Cendekia",
            job: "Alumni Association",
            address: "Jl. Example No. 14, Malang",
            linkage: "otm",
            funds: 850000,
            maxCapacity: 2,
            startDate: new Date(),
            maxSemester: 6,
            transferDate: 17,
            criteria: "Under 22 years old",
            isDetailVisible: false,
            allowAdminSelection: false,
          },
          {
            accountId: ota15Id,
            name: "Langkah Cerah",
            job: "Education Grant",
            address: "Jl. Example No. 15, Pontianak",
            linkage: "otm",
            funds: 875000,
            maxCapacity: 3,
            startDate: new Date(),
            maxSemester: 7,
            transferDate: 18,
            criteria: "Good academic standing",
            isDetailVisible: false,
            allowAdminSelection: true,
          },
        ])
        .onConflictDoNothing()
        .returning();

      console.log("OTA details seeded");

      await tx.insert(accountAdminDetailTable).values([
        {
          accountId: adminId,
          name: "Admin",
        },
        {
          accountId: bankes1Id,
          name: "Bankes 1",
        },
        {
          accountId: bankes2Id,
          name: "Bankes 2",
        },
        {
          accountId: pengurus1Id,
          name: "Pengurus 1",
        },
        {
          accountId: pengurus2Id,
          name: "Pengurus 2",
        },
      ]);

      console.log("Admin details seeded");

      await tx
        .insert(connectionTable)
        .values([
          {
            mahasiswaId: mahasiswa1Id,
            otaId: ota1Id,
            connectionStatus: "accepted",
            paidFor: 0,
          },
          {
            mahasiswaId: mahasiswa2Id,
            otaId: ota1Id,
            connectionStatus: "accepted",
            paidFor: 0,
          },
          {
            mahasiswaId: mahasiswa3Id,
            otaId: ota1Id,
            connectionStatus: "pending",
            paidFor: 0,
          },
          {
            mahasiswaId: mahasiswa8Id,
            otaId: ota2Id,
            connectionStatus: "accepted",
            paidFor: 0,
          },
        ])
        .onConflictDoNothing();

      console.log("Connections seeded");

      const currentDate = new Date();

      const thisMonthDateOta1 = setDate(
        currentDate,
        otaDetails[0].transferDate,
      );
      const thisMonthDateOta2 = setDate(
        currentDate,
        otaDetails[1].transferDate,
      );

      const nextMonthDateOta1 = setDate(
        addMonths(currentDate, 1),
        otaDetails[0].transferDate,
      );

      const nextMonthDateOta2 = setDate(
        addMonths(currentDate, 1),
        otaDetails[1].transferDate,
      );

      await tx.insert(transactionTable).values([
        {
          mahasiswaId: mahasiswa1Id,
          otaId: ota1Id,
          bill: 250000,
          amountPaid:
            currentDate.getDate() > otaDetails[0].transferDate ? 250000 : 0,
          paidAt:
            currentDate.getDate() > otaDetails[0].transferDate
              ? currentDate
              : null,
          dueDate: thisMonthDateOta1,
          transactionStatus:
            currentDate.getDate() > otaDetails[0].transferDate
              ? "paid"
              : "unpaid",
          transactionReceipt: null,
        },
        {
          mahasiswaId: mahasiswa2Id,
          otaId: ota1Id,
          bill: 250000,
          amountPaid:
            currentDate.getDate() > otaDetails[0].transferDate ? 250000 : 0,
          paidAt:
            currentDate.getDate() > otaDetails[0].transferDate
              ? currentDate
              : null,
          dueDate: thisMonthDateOta1,
          transactionStatus:
            currentDate.getDate() > otaDetails[0].transferDate
              ? "paid"
              : "unpaid",
        },
        {
          mahasiswaId: mahasiswa8Id,
          otaId: ota2Id,
          bill: 200000,
          amountPaid:
            currentDate.getDate() > otaDetails[1].transferDate ? 200000 : 0,
          paidAt:
            currentDate.getDate() > otaDetails[1].transferDate
              ? currentDate
              : null,
          dueDate: thisMonthDateOta2,
          transactionStatus:
            currentDate.getDate() > otaDetails[1].transferDate
              ? "paid"
              : "unpaid",
        },
        {
          mahasiswaId: mahasiswa1Id,
          otaId: ota1Id,
          bill: 250000,
          amountPaid: 0,
          paidAt: null,
          dueDate: nextMonthDateOta1,
          transactionStatus: "unpaid",
          transactionReceipt: null,
        },
        {
          mahasiswaId: mahasiswa2Id,
          otaId: ota1Id,
          bill: 250000,
          amountPaid: 0,
          paidAt: null,
          dueDate: nextMonthDateOta1,
          transactionStatus: "unpaid",
          transactionReceipt: null,
        },
        {
          mahasiswaId: mahasiswa8Id,
          otaId: ota2Id,
          bill: 200000,
          amountPaid: 0,
          paidAt: null,
          dueDate: nextMonthDateOta2,
          transactionStatus: "unpaid",
          transactionReceipt: null,
        },
      ]);

      console.log("Transactions seeded");
    });

    console.log("Database seeding completed successfully!");
  } catch (error) {
    console.error("Error seeding database:", error);
  } finally {
    console.log("Closing database connection...");
  }
}
