/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as AppIndexImport } from './routes/_app/index'
import { Route as AppVerifikasiAkunIndexImport } from './routes/_app/verifikasi-akun/index'
import { Route as AppStatusTransaksiIndexImport } from './routes/_app/status-transaksi/index'
import { Route as AppProfileIndexImport } from './routes/_app/profile/index'
import { Route as AppPersetujuanAsuhIndexImport } from './routes/_app/persetujuan-asuh/index'
import { Route as AppPendaftaranIndexImport } from './routes/_app/pendaftaran/index'
import { Route as AppPemasanganBotaIndexImport } from './routes/_app/pemasangan-bota/index'
import { Route as AppOrangTuaAsuhSayaIndexImport } from './routes/_app/orang-tua-asuh-saya/index'
import { Route as AppManajemenAkunIndexImport } from './routes/_app/manajemen-akun/index'
import { Route as AppMahasiswaAsuhSayaIndexImport } from './routes/_app/mahasiswa-asuh-saya/index'
import { Route as AppDataHubunganAsuhIndexImport } from './routes/_app/data-hubungan-asuh/index'
import { Route as AppDaftarTransferMahasiswaIndexImport } from './routes/_app/daftar-transfer-mahasiswa/index'
import { Route as AppDaftarTerminasiIndexImport } from './routes/_app/daftar-terminasi/index'
import { Route as AppDaftarTagihanIndexImport } from './routes/_app/daftar-tagihan/index'
import { Route as AppCariMahasiswaIndexImport } from './routes/_app/cari-mahasiswa/index'
import { Route as AppDaftarTerminasiMahasiswaIndexImport } from './routes/_app/daftar/terminasi-mahasiswa/index'
import { Route as AppAuthRegisterIndexImport } from './routes/_app/auth/register/index'
import { Route as AppAuthOtpVerificationIndexImport } from './routes/_app/auth/otp-verification/index'
import { Route as AppAuthLupaPasswordIndexImport } from './routes/_app/auth/lupa-password/index'
import { Route as AppAuthLoginIndexImport } from './routes/_app/auth/login/index'
import { Route as AppDetailMahasiswaDetailIdImport } from './routes/_app/detail/mahasiswa/$detailId'
import { Route as AppIntegrationsAzureKeyVaultOauth2CallbackIndexImport } from './routes/_app/integrations/azure-key-vault/oauth2/callback/index'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppVerifikasiAkunIndexRoute = AppVerifikasiAkunIndexImport.update({
  id: '/verifikasi-akun/',
  path: '/verifikasi-akun/',
  getParentRoute: () => AppRoute,
} as any)

const AppStatusTransaksiIndexRoute = AppStatusTransaksiIndexImport.update({
  id: '/status-transaksi/',
  path: '/status-transaksi/',
  getParentRoute: () => AppRoute,
} as any)

const AppProfileIndexRoute = AppProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)

const AppPersetujuanAsuhIndexRoute = AppPersetujuanAsuhIndexImport.update({
  id: '/persetujuan-asuh/',
  path: '/persetujuan-asuh/',
  getParentRoute: () => AppRoute,
} as any)

const AppPendaftaranIndexRoute = AppPendaftaranIndexImport.update({
  id: '/pendaftaran/',
  path: '/pendaftaran/',
  getParentRoute: () => AppRoute,
} as any)

const AppPemasanganBotaIndexRoute = AppPemasanganBotaIndexImport.update({
  id: '/pemasangan-bota/',
  path: '/pemasangan-bota/',
  getParentRoute: () => AppRoute,
} as any)

const AppOrangTuaAsuhSayaIndexRoute = AppOrangTuaAsuhSayaIndexImport.update({
  id: '/orang-tua-asuh-saya/',
  path: '/orang-tua-asuh-saya/',
  getParentRoute: () => AppRoute,
} as any)

const AppManajemenAkunIndexRoute = AppManajemenAkunIndexImport.update({
  id: '/manajemen-akun/',
  path: '/manajemen-akun/',
  getParentRoute: () => AppRoute,
} as any)

const AppMahasiswaAsuhSayaIndexRoute = AppMahasiswaAsuhSayaIndexImport.update({
  id: '/mahasiswa-asuh-saya/',
  path: '/mahasiswa-asuh-saya/',
  getParentRoute: () => AppRoute,
} as any)

const AppDataHubunganAsuhIndexRoute = AppDataHubunganAsuhIndexImport.update({
  id: '/data-hubungan-asuh/',
  path: '/data-hubungan-asuh/',
  getParentRoute: () => AppRoute,
} as any)

const AppDaftarTransferMahasiswaIndexRoute =
  AppDaftarTransferMahasiswaIndexImport.update({
    id: '/daftar-transfer-mahasiswa/',
    path: '/daftar-transfer-mahasiswa/',
    getParentRoute: () => AppRoute,
  } as any)

const AppDaftarTerminasiIndexRoute = AppDaftarTerminasiIndexImport.update({
  id: '/daftar-terminasi/',
  path: '/daftar-terminasi/',
  getParentRoute: () => AppRoute,
} as any)

const AppDaftarTagihanIndexRoute = AppDaftarTagihanIndexImport.update({
  id: '/daftar-tagihan/',
  path: '/daftar-tagihan/',
  getParentRoute: () => AppRoute,
} as any)

const AppCariMahasiswaIndexRoute = AppCariMahasiswaIndexImport.update({
  id: '/cari-mahasiswa/',
  path: '/cari-mahasiswa/',
  getParentRoute: () => AppRoute,
} as any)

const AppDaftarTerminasiMahasiswaIndexRoute =
  AppDaftarTerminasiMahasiswaIndexImport.update({
    id: '/daftar/terminasi-mahasiswa/',
    path: '/daftar/terminasi-mahasiswa/',
    getParentRoute: () => AppRoute,
  } as any)

const AppAuthRegisterIndexRoute = AppAuthRegisterIndexImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthOtpVerificationIndexRoute =
  AppAuthOtpVerificationIndexImport.update({
    id: '/auth/otp-verification/',
    path: '/auth/otp-verification/',
    getParentRoute: () => AppRoute,
  } as any)

const AppAuthLupaPasswordIndexRoute = AppAuthLupaPasswordIndexImport.update({
  id: '/auth/lupa-password/',
  path: '/auth/lupa-password/',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthLoginIndexRoute = AppAuthLoginIndexImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => AppRoute,
} as any)

const AppDetailMahasiswaDetailIdRoute = AppDetailMahasiswaDetailIdImport.update(
  {
    id: '/detail/mahasiswa/$detailId',
    path: '/detail/mahasiswa/$detailId',
    getParentRoute: () => AppRoute,
  } as any,
)

const AppIntegrationsAzureKeyVaultOauth2CallbackIndexRoute =
  AppIntegrationsAzureKeyVaultOauth2CallbackIndexImport.update({
    id: '/integrations/azure-key-vault/oauth2/callback/',
    path: '/integrations/azure-key-vault/oauth2/callback/',
    getParentRoute: () => AppRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/cari-mahasiswa/': {
      id: '/_app/cari-mahasiswa/'
      path: '/cari-mahasiswa'
      fullPath: '/cari-mahasiswa'
      preLoaderRoute: typeof AppCariMahasiswaIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/daftar-tagihan/': {
      id: '/_app/daftar-tagihan/'
      path: '/daftar-tagihan'
      fullPath: '/daftar-tagihan'
      preLoaderRoute: typeof AppDaftarTagihanIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/daftar-terminasi/': {
      id: '/_app/daftar-terminasi/'
      path: '/daftar-terminasi'
      fullPath: '/daftar-terminasi'
      preLoaderRoute: typeof AppDaftarTerminasiIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/daftar-transfer-mahasiswa/': {
      id: '/_app/daftar-transfer-mahasiswa/'
      path: '/daftar-transfer-mahasiswa'
      fullPath: '/daftar-transfer-mahasiswa'
      preLoaderRoute: typeof AppDaftarTransferMahasiswaIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/data-hubungan-asuh/': {
      id: '/_app/data-hubungan-asuh/'
      path: '/data-hubungan-asuh'
      fullPath: '/data-hubungan-asuh'
      preLoaderRoute: typeof AppDataHubunganAsuhIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/mahasiswa-asuh-saya/': {
      id: '/_app/mahasiswa-asuh-saya/'
      path: '/mahasiswa-asuh-saya'
      fullPath: '/mahasiswa-asuh-saya'
      preLoaderRoute: typeof AppMahasiswaAsuhSayaIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/manajemen-akun/': {
      id: '/_app/manajemen-akun/'
      path: '/manajemen-akun'
      fullPath: '/manajemen-akun'
      preLoaderRoute: typeof AppManajemenAkunIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/orang-tua-asuh-saya/': {
      id: '/_app/orang-tua-asuh-saya/'
      path: '/orang-tua-asuh-saya'
      fullPath: '/orang-tua-asuh-saya'
      preLoaderRoute: typeof AppOrangTuaAsuhSayaIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/pemasangan-bota/': {
      id: '/_app/pemasangan-bota/'
      path: '/pemasangan-bota'
      fullPath: '/pemasangan-bota'
      preLoaderRoute: typeof AppPemasanganBotaIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/pendaftaran/': {
      id: '/_app/pendaftaran/'
      path: '/pendaftaran'
      fullPath: '/pendaftaran'
      preLoaderRoute: typeof AppPendaftaranIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/persetujuan-asuh/': {
      id: '/_app/persetujuan-asuh/'
      path: '/persetujuan-asuh'
      fullPath: '/persetujuan-asuh'
      preLoaderRoute: typeof AppPersetujuanAsuhIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/status-transaksi/': {
      id: '/_app/status-transaksi/'
      path: '/status-transaksi'
      fullPath: '/status-transaksi'
      preLoaderRoute: typeof AppStatusTransaksiIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/verifikasi-akun/': {
      id: '/_app/verifikasi-akun/'
      path: '/verifikasi-akun'
      fullPath: '/verifikasi-akun'
      preLoaderRoute: typeof AppVerifikasiAkunIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/detail/mahasiswa/$detailId': {
      id: '/_app/detail/mahasiswa/$detailId'
      path: '/detail/mahasiswa/$detailId'
      fullPath: '/detail/mahasiswa/$detailId'
      preLoaderRoute: typeof AppDetailMahasiswaDetailIdImport
      parentRoute: typeof AppImport
    }
    '/_app/auth/login/': {
      id: '/_app/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AppAuthLoginIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/auth/lupa-password/': {
      id: '/_app/auth/lupa-password/'
      path: '/auth/lupa-password'
      fullPath: '/auth/lupa-password'
      preLoaderRoute: typeof AppAuthLupaPasswordIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/auth/otp-verification/': {
      id: '/_app/auth/otp-verification/'
      path: '/auth/otp-verification'
      fullPath: '/auth/otp-verification'
      preLoaderRoute: typeof AppAuthOtpVerificationIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/auth/register/': {
      id: '/_app/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AppAuthRegisterIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/daftar/terminasi-mahasiswa/': {
      id: '/_app/daftar/terminasi-mahasiswa/'
      path: '/daftar/terminasi-mahasiswa'
      fullPath: '/daftar/terminasi-mahasiswa'
      preLoaderRoute: typeof AppDaftarTerminasiMahasiswaIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/integrations/azure-key-vault/oauth2/callback/': {
      id: '/_app/integrations/azure-key-vault/oauth2/callback/'
      path: '/integrations/azure-key-vault/oauth2/callback'
      fullPath: '/integrations/azure-key-vault/oauth2/callback'
      preLoaderRoute: typeof AppIntegrationsAzureKeyVaultOauth2CallbackIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCariMahasiswaIndexRoute: typeof AppCariMahasiswaIndexRoute
  AppDaftarTagihanIndexRoute: typeof AppDaftarTagihanIndexRoute
  AppDaftarTerminasiIndexRoute: typeof AppDaftarTerminasiIndexRoute
  AppDaftarTransferMahasiswaIndexRoute: typeof AppDaftarTransferMahasiswaIndexRoute
  AppDataHubunganAsuhIndexRoute: typeof AppDataHubunganAsuhIndexRoute
  AppMahasiswaAsuhSayaIndexRoute: typeof AppMahasiswaAsuhSayaIndexRoute
  AppManajemenAkunIndexRoute: typeof AppManajemenAkunIndexRoute
  AppOrangTuaAsuhSayaIndexRoute: typeof AppOrangTuaAsuhSayaIndexRoute
  AppPemasanganBotaIndexRoute: typeof AppPemasanganBotaIndexRoute
  AppPendaftaranIndexRoute: typeof AppPendaftaranIndexRoute
  AppPersetujuanAsuhIndexRoute: typeof AppPersetujuanAsuhIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppStatusTransaksiIndexRoute: typeof AppStatusTransaksiIndexRoute
  AppVerifikasiAkunIndexRoute: typeof AppVerifikasiAkunIndexRoute
  AppDetailMahasiswaDetailIdRoute: typeof AppDetailMahasiswaDetailIdRoute
  AppAuthLoginIndexRoute: typeof AppAuthLoginIndexRoute
  AppAuthLupaPasswordIndexRoute: typeof AppAuthLupaPasswordIndexRoute
  AppAuthOtpVerificationIndexRoute: typeof AppAuthOtpVerificationIndexRoute
  AppAuthRegisterIndexRoute: typeof AppAuthRegisterIndexRoute
  AppDaftarTerminasiMahasiswaIndexRoute: typeof AppDaftarTerminasiMahasiswaIndexRoute
  AppIntegrationsAzureKeyVaultOauth2CallbackIndexRoute: typeof AppIntegrationsAzureKeyVaultOauth2CallbackIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCariMahasiswaIndexRoute: AppCariMahasiswaIndexRoute,
  AppDaftarTagihanIndexRoute: AppDaftarTagihanIndexRoute,
  AppDaftarTerminasiIndexRoute: AppDaftarTerminasiIndexRoute,
  AppDaftarTransferMahasiswaIndexRoute: AppDaftarTransferMahasiswaIndexRoute,
  AppDataHubunganAsuhIndexRoute: AppDataHubunganAsuhIndexRoute,
  AppMahasiswaAsuhSayaIndexRoute: AppMahasiswaAsuhSayaIndexRoute,
  AppManajemenAkunIndexRoute: AppManajemenAkunIndexRoute,
  AppOrangTuaAsuhSayaIndexRoute: AppOrangTuaAsuhSayaIndexRoute,
  AppPemasanganBotaIndexRoute: AppPemasanganBotaIndexRoute,
  AppPendaftaranIndexRoute: AppPendaftaranIndexRoute,
  AppPersetujuanAsuhIndexRoute: AppPersetujuanAsuhIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppStatusTransaksiIndexRoute: AppStatusTransaksiIndexRoute,
  AppVerifikasiAkunIndexRoute: AppVerifikasiAkunIndexRoute,
  AppDetailMahasiswaDetailIdRoute: AppDetailMahasiswaDetailIdRoute,
  AppAuthLoginIndexRoute: AppAuthLoginIndexRoute,
  AppAuthLupaPasswordIndexRoute: AppAuthLupaPasswordIndexRoute,
  AppAuthOtpVerificationIndexRoute: AppAuthOtpVerificationIndexRoute,
  AppAuthRegisterIndexRoute: AppAuthRegisterIndexRoute,
  AppDaftarTerminasiMahasiswaIndexRoute: AppDaftarTerminasiMahasiswaIndexRoute,
  AppIntegrationsAzureKeyVaultOauth2CallbackIndexRoute:
    AppIntegrationsAzureKeyVaultOauth2CallbackIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/': typeof AppIndexRoute
  '/cari-mahasiswa': typeof AppCariMahasiswaIndexRoute
  '/daftar-tagihan': typeof AppDaftarTagihanIndexRoute
  '/daftar-terminasi': typeof AppDaftarTerminasiIndexRoute
  '/daftar-transfer-mahasiswa': typeof AppDaftarTransferMahasiswaIndexRoute
  '/data-hubungan-asuh': typeof AppDataHubunganAsuhIndexRoute
  '/mahasiswa-asuh-saya': typeof AppMahasiswaAsuhSayaIndexRoute
  '/manajemen-akun': typeof AppManajemenAkunIndexRoute
  '/orang-tua-asuh-saya': typeof AppOrangTuaAsuhSayaIndexRoute
  '/pemasangan-bota': typeof AppPemasanganBotaIndexRoute
  '/pendaftaran': typeof AppPendaftaranIndexRoute
  '/persetujuan-asuh': typeof AppPersetujuanAsuhIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/status-transaksi': typeof AppStatusTransaksiIndexRoute
  '/verifikasi-akun': typeof AppVerifikasiAkunIndexRoute
  '/detail/mahasiswa/$detailId': typeof AppDetailMahasiswaDetailIdRoute
  '/auth/login': typeof AppAuthLoginIndexRoute
  '/auth/lupa-password': typeof AppAuthLupaPasswordIndexRoute
  '/auth/otp-verification': typeof AppAuthOtpVerificationIndexRoute
  '/auth/register': typeof AppAuthRegisterIndexRoute
  '/daftar/terminasi-mahasiswa': typeof AppDaftarTerminasiMahasiswaIndexRoute
  '/integrations/azure-key-vault/oauth2/callback': typeof AppIntegrationsAzureKeyVaultOauth2CallbackIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/cari-mahasiswa': typeof AppCariMahasiswaIndexRoute
  '/daftar-tagihan': typeof AppDaftarTagihanIndexRoute
  '/daftar-terminasi': typeof AppDaftarTerminasiIndexRoute
  '/daftar-transfer-mahasiswa': typeof AppDaftarTransferMahasiswaIndexRoute
  '/data-hubungan-asuh': typeof AppDataHubunganAsuhIndexRoute
  '/mahasiswa-asuh-saya': typeof AppMahasiswaAsuhSayaIndexRoute
  '/manajemen-akun': typeof AppManajemenAkunIndexRoute
  '/orang-tua-asuh-saya': typeof AppOrangTuaAsuhSayaIndexRoute
  '/pemasangan-bota': typeof AppPemasanganBotaIndexRoute
  '/pendaftaran': typeof AppPendaftaranIndexRoute
  '/persetujuan-asuh': typeof AppPersetujuanAsuhIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/status-transaksi': typeof AppStatusTransaksiIndexRoute
  '/verifikasi-akun': typeof AppVerifikasiAkunIndexRoute
  '/detail/mahasiswa/$detailId': typeof AppDetailMahasiswaDetailIdRoute
  '/auth/login': typeof AppAuthLoginIndexRoute
  '/auth/lupa-password': typeof AppAuthLupaPasswordIndexRoute
  '/auth/otp-verification': typeof AppAuthOtpVerificationIndexRoute
  '/auth/register': typeof AppAuthRegisterIndexRoute
  '/daftar/terminasi-mahasiswa': typeof AppDaftarTerminasiMahasiswaIndexRoute
  '/integrations/azure-key-vault/oauth2/callback': typeof AppIntegrationsAzureKeyVaultOauth2CallbackIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/cari-mahasiswa/': typeof AppCariMahasiswaIndexRoute
  '/_app/daftar-tagihan/': typeof AppDaftarTagihanIndexRoute
  '/_app/daftar-terminasi/': typeof AppDaftarTerminasiIndexRoute
  '/_app/daftar-transfer-mahasiswa/': typeof AppDaftarTransferMahasiswaIndexRoute
  '/_app/data-hubungan-asuh/': typeof AppDataHubunganAsuhIndexRoute
  '/_app/mahasiswa-asuh-saya/': typeof AppMahasiswaAsuhSayaIndexRoute
  '/_app/manajemen-akun/': typeof AppManajemenAkunIndexRoute
  '/_app/orang-tua-asuh-saya/': typeof AppOrangTuaAsuhSayaIndexRoute
  '/_app/pemasangan-bota/': typeof AppPemasanganBotaIndexRoute
  '/_app/pendaftaran/': typeof AppPendaftaranIndexRoute
  '/_app/persetujuan-asuh/': typeof AppPersetujuanAsuhIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/status-transaksi/': typeof AppStatusTransaksiIndexRoute
  '/_app/verifikasi-akun/': typeof AppVerifikasiAkunIndexRoute
  '/_app/detail/mahasiswa/$detailId': typeof AppDetailMahasiswaDetailIdRoute
  '/_app/auth/login/': typeof AppAuthLoginIndexRoute
  '/_app/auth/lupa-password/': typeof AppAuthLupaPasswordIndexRoute
  '/_app/auth/otp-verification/': typeof AppAuthOtpVerificationIndexRoute
  '/_app/auth/register/': typeof AppAuthRegisterIndexRoute
  '/_app/daftar/terminasi-mahasiswa/': typeof AppDaftarTerminasiMahasiswaIndexRoute
  '/_app/integrations/azure-key-vault/oauth2/callback/': typeof AppIntegrationsAzureKeyVaultOauth2CallbackIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/cari-mahasiswa'
    | '/daftar-tagihan'
    | '/daftar-terminasi'
    | '/daftar-transfer-mahasiswa'
    | '/data-hubungan-asuh'
    | '/mahasiswa-asuh-saya'
    | '/manajemen-akun'
    | '/orang-tua-asuh-saya'
    | '/pemasangan-bota'
    | '/pendaftaran'
    | '/persetujuan-asuh'
    | '/profile'
    | '/status-transaksi'
    | '/verifikasi-akun'
    | '/detail/mahasiswa/$detailId'
    | '/auth/login'
    | '/auth/lupa-password'
    | '/auth/otp-verification'
    | '/auth/register'
    | '/daftar/terminasi-mahasiswa'
    | '/integrations/azure-key-vault/oauth2/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cari-mahasiswa'
    | '/daftar-tagihan'
    | '/daftar-terminasi'
    | '/daftar-transfer-mahasiswa'
    | '/data-hubungan-asuh'
    | '/mahasiswa-asuh-saya'
    | '/manajemen-akun'
    | '/orang-tua-asuh-saya'
    | '/pemasangan-bota'
    | '/pendaftaran'
    | '/persetujuan-asuh'
    | '/profile'
    | '/status-transaksi'
    | '/verifikasi-akun'
    | '/detail/mahasiswa/$detailId'
    | '/auth/login'
    | '/auth/lupa-password'
    | '/auth/otp-verification'
    | '/auth/register'
    | '/daftar/terminasi-mahasiswa'
    | '/integrations/azure-key-vault/oauth2/callback'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/cari-mahasiswa/'
    | '/_app/daftar-tagihan/'
    | '/_app/daftar-terminasi/'
    | '/_app/daftar-transfer-mahasiswa/'
    | '/_app/data-hubungan-asuh/'
    | '/_app/mahasiswa-asuh-saya/'
    | '/_app/manajemen-akun/'
    | '/_app/orang-tua-asuh-saya/'
    | '/_app/pemasangan-bota/'
    | '/_app/pendaftaran/'
    | '/_app/persetujuan-asuh/'
    | '/_app/profile/'
    | '/_app/status-transaksi/'
    | '/_app/verifikasi-akun/'
    | '/_app/detail/mahasiswa/$detailId'
    | '/_app/auth/login/'
    | '/_app/auth/lupa-password/'
    | '/_app/auth/otp-verification/'
    | '/_app/auth/register/'
    | '/_app/daftar/terminasi-mahasiswa/'
    | '/_app/integrations/azure-key-vault/oauth2/callback/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/",
        "/_app/cari-mahasiswa/",
        "/_app/daftar-tagihan/",
        "/_app/daftar-terminasi/",
        "/_app/daftar-transfer-mahasiswa/",
        "/_app/data-hubungan-asuh/",
        "/_app/mahasiswa-asuh-saya/",
        "/_app/manajemen-akun/",
        "/_app/orang-tua-asuh-saya/",
        "/_app/pemasangan-bota/",
        "/_app/pendaftaran/",
        "/_app/persetujuan-asuh/",
        "/_app/profile/",
        "/_app/status-transaksi/",
        "/_app/verifikasi-akun/",
        "/_app/detail/mahasiswa/$detailId",
        "/_app/auth/login/",
        "/_app/auth/lupa-password/",
        "/_app/auth/otp-verification/",
        "/_app/auth/register/",
        "/_app/daftar/terminasi-mahasiswa/",
        "/_app/integrations/azure-key-vault/oauth2/callback/"
      ]
    },
    "/_app/": {
      "filePath": "_app/index.tsx",
      "parent": "/_app"
    },
    "/_app/cari-mahasiswa/": {
      "filePath": "_app/cari-mahasiswa/index.tsx",
      "parent": "/_app"
    },
    "/_app/daftar-tagihan/": {
      "filePath": "_app/daftar-tagihan/index.tsx",
      "parent": "/_app"
    },
    "/_app/daftar-terminasi/": {
      "filePath": "_app/daftar-terminasi/index.tsx",
      "parent": "/_app"
    },
    "/_app/daftar-transfer-mahasiswa/": {
      "filePath": "_app/daftar-transfer-mahasiswa/index.tsx",
      "parent": "/_app"
    },
    "/_app/data-hubungan-asuh/": {
      "filePath": "_app/data-hubungan-asuh/index.tsx",
      "parent": "/_app"
    },
    "/_app/mahasiswa-asuh-saya/": {
      "filePath": "_app/mahasiswa-asuh-saya/index.tsx",
      "parent": "/_app"
    },
    "/_app/manajemen-akun/": {
      "filePath": "_app/manajemen-akun/index.tsx",
      "parent": "/_app"
    },
    "/_app/orang-tua-asuh-saya/": {
      "filePath": "_app/orang-tua-asuh-saya/index.tsx",
      "parent": "/_app"
    },
    "/_app/pemasangan-bota/": {
      "filePath": "_app/pemasangan-bota/index.tsx",
      "parent": "/_app"
    },
    "/_app/pendaftaran/": {
      "filePath": "_app/pendaftaran/index.tsx",
      "parent": "/_app"
    },
    "/_app/persetujuan-asuh/": {
      "filePath": "_app/persetujuan-asuh/index.tsx",
      "parent": "/_app"
    },
    "/_app/profile/": {
      "filePath": "_app/profile/index.tsx",
      "parent": "/_app"
    },
    "/_app/status-transaksi/": {
      "filePath": "_app/status-transaksi/index.tsx",
      "parent": "/_app"
    },
    "/_app/verifikasi-akun/": {
      "filePath": "_app/verifikasi-akun/index.tsx",
      "parent": "/_app"
    },
    "/_app/detail/mahasiswa/$detailId": {
      "filePath": "_app/detail/mahasiswa/$detailId.tsx",
      "parent": "/_app"
    },
    "/_app/auth/login/": {
      "filePath": "_app/auth/login/index.tsx",
      "parent": "/_app"
    },
    "/_app/auth/lupa-password/": {
      "filePath": "_app/auth/lupa-password/index.tsx",
      "parent": "/_app"
    },
    "/_app/auth/otp-verification/": {
      "filePath": "_app/auth/otp-verification/index.tsx",
      "parent": "/_app"
    },
    "/_app/auth/register/": {
      "filePath": "_app/auth/register/index.tsx",
      "parent": "/_app"
    },
    "/_app/daftar/terminasi-mahasiswa/": {
      "filePath": "_app/daftar/terminasi-mahasiswa/index.tsx",
      "parent": "/_app"
    },
    "/_app/integrations/azure-key-vault/oauth2/callback/": {
      "filePath": "_app/integrations/azure-key-vault/oauth2/callback/index.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
