/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppVerifikasiAkunIndexRouteImport } from './routes/_app/verifikasi-akun/index'
import { Route as AppStatusTransaksiIndexRouteImport } from './routes/_app/status-transaksi/index'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppPersetujuanAsuhIndexRouteImport } from './routes/_app/persetujuan-asuh/index'
import { Route as AppPendaftaranIndexRouteImport } from './routes/_app/pendaftaran/index'
import { Route as AppPemasanganBotaIndexRouteImport } from './routes/_app/pemasangan-bota/index'
import { Route as AppOrangTuaAsuhSayaIndexRouteImport } from './routes/_app/orang-tua-asuh-saya/index'
import { Route as AppManajemenAkunIndexRouteImport } from './routes/_app/manajemen-akun/index'
import { Route as AppMahasiswaAsuhSayaIndexRouteImport } from './routes/_app/mahasiswa-asuh-saya/index'
import { Route as AppGroupsIndexRouteImport } from './routes/_app/groups/index'
import { Route as AppDataHubunganAsuhIndexRouteImport } from './routes/_app/data-hubungan-asuh/index'
import { Route as AppDaftarTransferMahasiswaIndexRouteImport } from './routes/_app/daftar-transfer-mahasiswa/index'
import { Route as AppDaftarTerminasiIndexRouteImport } from './routes/_app/daftar-terminasi/index'
import { Route as AppDaftarTagihanIndexRouteImport } from './routes/_app/daftar-tagihan/index'
import { Route as AppCariMahasiswaIndexRouteImport } from './routes/_app/cari-mahasiswa/index'
import { Route as AppGroupsGroupIdRouteImport } from './routes/_app/groups/$groupId'
import { Route as AppDaftarTerminasiMahasiswaIndexRouteImport } from './routes/_app/daftar/terminasi-mahasiswa/index'
import { Route as AppAuthRegisterIndexRouteImport } from './routes/_app/auth/register/index'
import { Route as AppAuthOtpVerificationIndexRouteImport } from './routes/_app/auth/otp-verification/index'
import { Route as AppAuthLupaPasswordIndexRouteImport } from './routes/_app/auth/lupa-password/index'
import { Route as AppAuthLoginIndexRouteImport } from './routes/_app/auth/login/index'
import { Route as AppDetailMahasiswaDetailIdRouteImport } from './routes/_app/detail/mahasiswa/$detailId'
import { Route as AppIntegrationsAzureKeyVaultOauth2CallbackIndexRouteImport } from './routes/_app/integrations/azure-key-vault/oauth2/callback/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifikasiAkunIndexRoute = AppVerifikasiAkunIndexRouteImport.update({
  id: '/verifikasi-akun/',
  path: '/verifikasi-akun/',
  getParentRoute: () => AppRoute,
} as any)
const AppStatusTransaksiIndexRoute = AppStatusTransaksiIndexRouteImport.update({
  id: '/status-transaksi/',
  path: '/status-transaksi/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppPersetujuanAsuhIndexRoute = AppPersetujuanAsuhIndexRouteImport.update({
  id: '/persetujuan-asuh/',
  path: '/persetujuan-asuh/',
  getParentRoute: () => AppRoute,
} as any)
const AppPendaftaranIndexRoute = AppPendaftaranIndexRouteImport.update({
  id: '/pendaftaran/',
  path: '/pendaftaran/',
  getParentRoute: () => AppRoute,
} as any)
const AppPemasanganBotaIndexRoute = AppPemasanganBotaIndexRouteImport.update({
  id: '/pemasangan-bota/',
  path: '/pemasangan-bota/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrangTuaAsuhSayaIndexRoute =
  AppOrangTuaAsuhSayaIndexRouteImport.update({
    id: '/orang-tua-asuh-saya/',
    path: '/orang-tua-asuh-saya/',
    getParentRoute: () => AppRoute,
  } as any)
const AppManajemenAkunIndexRoute = AppManajemenAkunIndexRouteImport.update({
  id: '/manajemen-akun/',
  path: '/manajemen-akun/',
  getParentRoute: () => AppRoute,
} as any)
const AppMahasiswaAsuhSayaIndexRoute =
  AppMahasiswaAsuhSayaIndexRouteImport.update({
    id: '/mahasiswa-asuh-saya/',
    path: '/mahasiswa-asuh-saya/',
    getParentRoute: () => AppRoute,
  } as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any)
const AppDataHubunganAsuhIndexRoute =
  AppDataHubunganAsuhIndexRouteImport.update({
    id: '/data-hubungan-asuh/',
    path: '/data-hubungan-asuh/',
    getParentRoute: () => AppRoute,
  } as any)
const AppDaftarTransferMahasiswaIndexRoute =
  AppDaftarTransferMahasiswaIndexRouteImport.update({
    id: '/daftar-transfer-mahasiswa/',
    path: '/daftar-transfer-mahasiswa/',
    getParentRoute: () => AppRoute,
  } as any)
const AppDaftarTerminasiIndexRoute = AppDaftarTerminasiIndexRouteImport.update({
  id: '/daftar-terminasi/',
  path: '/daftar-terminasi/',
  getParentRoute: () => AppRoute,
} as any)
const AppDaftarTagihanIndexRoute = AppDaftarTagihanIndexRouteImport.update({
  id: '/daftar-tagihan/',
  path: '/daftar-tagihan/',
  getParentRoute: () => AppRoute,
} as any)
const AppCariMahasiswaIndexRoute = AppCariMahasiswaIndexRouteImport.update({
  id: '/cari-mahasiswa/',
  path: '/cari-mahasiswa/',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsGroupIdRoute = AppGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const AppDaftarTerminasiMahasiswaIndexRoute =
  AppDaftarTerminasiMahasiswaIndexRouteImport.update({
    id: '/daftar/terminasi-mahasiswa/',
    path: '/daftar/terminasi-mahasiswa/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthRegisterIndexRoute = AppAuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthOtpVerificationIndexRoute =
  AppAuthOtpVerificationIndexRouteImport.update({
    id: '/auth/otp-verification/',
    path: '/auth/otp-verification/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthLupaPasswordIndexRoute =
  AppAuthLupaPasswordIndexRouteImport.update({
    id: '/auth/lupa-password/',
    path: '/auth/lupa-password/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthLoginIndexRoute = AppAuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => AppRoute,
} as any)
const AppDetailMahasiswaDetailIdRoute =
  AppDetailMahasiswaDetailIdRouteImport.update({
    id: '/detail/mahasiswa/$detailId',
    path: '/detail/mahasiswa/$detailId',
    getParentRoute: () => AppRoute,
  } as any)
const AppIntegrationsAzureKeyVaultOauth2CallbackIndexRoute =
  AppIntegrationsAzureKeyVaultOauth2CallbackIndexRouteImport.update({
    id: '/integrations/azure-key-vault/oauth2/callback/',
    path: '/integrations/azure-key-vault/oauth2/callback/',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/cari-mahasiswa/': typeof AppCariMahasiswaIndexRoute
  '/daftar-tagihan/': typeof AppDaftarTagihanIndexRoute
  '/daftar-terminasi/': typeof AppDaftarTerminasiIndexRoute
  '/daftar-transfer-mahasiswa/': typeof AppDaftarTransferMahasiswaIndexRoute
  '/data-hubungan-asuh/': typeof AppDataHubunganAsuhIndexRoute
  '/groups/': typeof AppGroupsIndexRoute
  '/mahasiswa-asuh-saya/': typeof AppMahasiswaAsuhSayaIndexRoute
  '/manajemen-akun/': typeof AppManajemenAkunIndexRoute
  '/orang-tua-asuh-saya/': typeof AppOrangTuaAsuhSayaIndexRoute
  '/pemasangan-bota/': typeof AppPemasanganBotaIndexRoute
  '/pendaftaran/': typeof AppPendaftaranIndexRoute
  '/persetujuan-asuh/': typeof AppPersetujuanAsuhIndexRoute
  '/profile/': typeof AppProfileIndexRoute
  '/status-transaksi/': typeof AppStatusTransaksiIndexRoute
  '/verifikasi-akun/': typeof AppVerifikasiAkunIndexRoute
  '/detail/mahasiswa/$detailId': typeof AppDetailMahasiswaDetailIdRoute
  '/auth/login/': typeof AppAuthLoginIndexRoute
  '/auth/lupa-password/': typeof AppAuthLupaPasswordIndexRoute
  '/auth/otp-verification/': typeof AppAuthOtpVerificationIndexRoute
  '/auth/register/': typeof AppAuthRegisterIndexRoute
  '/daftar/terminasi-mahasiswa/': typeof AppDaftarTerminasiMahasiswaIndexRoute
  '/integrations/azure-key-vault/oauth2/callback/': typeof AppIntegrationsAzureKeyVaultOauth2CallbackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/cari-mahasiswa': typeof AppCariMahasiswaIndexRoute
  '/daftar-tagihan': typeof AppDaftarTagihanIndexRoute
  '/daftar-terminasi': typeof AppDaftarTerminasiIndexRoute
  '/daftar-transfer-mahasiswa': typeof AppDaftarTransferMahasiswaIndexRoute
  '/data-hubungan-asuh': typeof AppDataHubunganAsuhIndexRoute
  '/groups': typeof AppGroupsIndexRoute
  '/mahasiswa-asuh-saya': typeof AppMahasiswaAsuhSayaIndexRoute
  '/manajemen-akun': typeof AppManajemenAkunIndexRoute
  '/orang-tua-asuh-saya': typeof AppOrangTuaAsuhSayaIndexRoute
  '/pemasangan-bota': typeof AppPemasanganBotaIndexRoute
  '/pendaftaran': typeof AppPendaftaranIndexRoute
  '/persetujuan-asuh': typeof AppPersetujuanAsuhIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/status-transaksi': typeof AppStatusTransaksiIndexRoute
  '/verifikasi-akun': typeof AppVerifikasiAkunIndexRoute
  '/detail/mahasiswa/$detailId': typeof AppDetailMahasiswaDetailIdRoute
  '/auth/login': typeof AppAuthLoginIndexRoute
  '/auth/lupa-password': typeof AppAuthLupaPasswordIndexRoute
  '/auth/otp-verification': typeof AppAuthOtpVerificationIndexRoute
  '/auth/register': typeof AppAuthRegisterIndexRoute
  '/daftar/terminasi-mahasiswa': typeof AppDaftarTerminasiMahasiswaIndexRoute
  '/integrations/azure-key-vault/oauth2/callback': typeof AppIntegrationsAzureKeyVaultOauth2CallbackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/_app/cari-mahasiswa/': typeof AppCariMahasiswaIndexRoute
  '/_app/daftar-tagihan/': typeof AppDaftarTagihanIndexRoute
  '/_app/daftar-terminasi/': typeof AppDaftarTerminasiIndexRoute
  '/_app/daftar-transfer-mahasiswa/': typeof AppDaftarTransferMahasiswaIndexRoute
  '/_app/data-hubungan-asuh/': typeof AppDataHubunganAsuhIndexRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
  '/_app/mahasiswa-asuh-saya/': typeof AppMahasiswaAsuhSayaIndexRoute
  '/_app/manajemen-akun/': typeof AppManajemenAkunIndexRoute
  '/_app/orang-tua-asuh-saya/': typeof AppOrangTuaAsuhSayaIndexRoute
  '/_app/pemasangan-bota/': typeof AppPemasanganBotaIndexRoute
  '/_app/pendaftaran/': typeof AppPendaftaranIndexRoute
  '/_app/persetujuan-asuh/': typeof AppPersetujuanAsuhIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/status-transaksi/': typeof AppStatusTransaksiIndexRoute
  '/_app/verifikasi-akun/': typeof AppVerifikasiAkunIndexRoute
  '/_app/detail/mahasiswa/$detailId': typeof AppDetailMahasiswaDetailIdRoute
  '/_app/auth/login/': typeof AppAuthLoginIndexRoute
  '/_app/auth/lupa-password/': typeof AppAuthLupaPasswordIndexRoute
  '/_app/auth/otp-verification/': typeof AppAuthOtpVerificationIndexRoute
  '/_app/auth/register/': typeof AppAuthRegisterIndexRoute
  '/_app/daftar/terminasi-mahasiswa/': typeof AppDaftarTerminasiMahasiswaIndexRoute
  '/_app/integrations/azure-key-vault/oauth2/callback/': typeof AppIntegrationsAzureKeyVaultOauth2CallbackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups/$groupId'
    | '/cari-mahasiswa/'
    | '/daftar-tagihan/'
    | '/daftar-terminasi/'
    | '/daftar-transfer-mahasiswa/'
    | '/data-hubungan-asuh/'
    | '/groups/'
    | '/mahasiswa-asuh-saya/'
    | '/manajemen-akun/'
    | '/orang-tua-asuh-saya/'
    | '/pemasangan-bota/'
    | '/pendaftaran/'
    | '/persetujuan-asuh/'
    | '/profile/'
    | '/status-transaksi/'
    | '/verifikasi-akun/'
    | '/detail/mahasiswa/$detailId'
    | '/auth/login/'
    | '/auth/lupa-password/'
    | '/auth/otp-verification/'
    | '/auth/register/'
    | '/daftar/terminasi-mahasiswa/'
    | '/integrations/azure-key-vault/oauth2/callback/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups/$groupId'
    | '/cari-mahasiswa'
    | '/daftar-tagihan'
    | '/daftar-terminasi'
    | '/daftar-transfer-mahasiswa'
    | '/data-hubungan-asuh'
    | '/groups'
    | '/mahasiswa-asuh-saya'
    | '/manajemen-akun'
    | '/orang-tua-asuh-saya'
    | '/pemasangan-bota'
    | '/pendaftaran'
    | '/persetujuan-asuh'
    | '/profile'
    | '/status-transaksi'
    | '/verifikasi-akun'
    | '/detail/mahasiswa/$detailId'
    | '/auth/login'
    | '/auth/lupa-password'
    | '/auth/otp-verification'
    | '/auth/register'
    | '/daftar/terminasi-mahasiswa'
    | '/integrations/azure-key-vault/oauth2/callback'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/groups/$groupId'
    | '/_app/cari-mahasiswa/'
    | '/_app/daftar-tagihan/'
    | '/_app/daftar-terminasi/'
    | '/_app/daftar-transfer-mahasiswa/'
    | '/_app/data-hubungan-asuh/'
    | '/_app/groups/'
    | '/_app/mahasiswa-asuh-saya/'
    | '/_app/manajemen-akun/'
    | '/_app/orang-tua-asuh-saya/'
    | '/_app/pemasangan-bota/'
    | '/_app/pendaftaran/'
    | '/_app/persetujuan-asuh/'
    | '/_app/profile/'
    | '/_app/status-transaksi/'
    | '/_app/verifikasi-akun/'
    | '/_app/detail/mahasiswa/$detailId'
    | '/_app/auth/login/'
    | '/_app/auth/lupa-password/'
    | '/_app/auth/otp-verification/'
    | '/_app/auth/register/'
    | '/_app/daftar/terminasi-mahasiswa/'
    | '/_app/integrations/azure-key-vault/oauth2/callback/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/verifikasi-akun/': {
      id: '/_app/verifikasi-akun/'
      path: '/verifikasi-akun'
      fullPath: '/verifikasi-akun/'
      preLoaderRoute: typeof AppVerifikasiAkunIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/status-transaksi/': {
      id: '/_app/status-transaksi/'
      path: '/status-transaksi'
      fullPath: '/status-transaksi/'
      preLoaderRoute: typeof AppStatusTransaksiIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/persetujuan-asuh/': {
      id: '/_app/persetujuan-asuh/'
      path: '/persetujuan-asuh'
      fullPath: '/persetujuan-asuh/'
      preLoaderRoute: typeof AppPersetujuanAsuhIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pendaftaran/': {
      id: '/_app/pendaftaran/'
      path: '/pendaftaran'
      fullPath: '/pendaftaran/'
      preLoaderRoute: typeof AppPendaftaranIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pemasangan-bota/': {
      id: '/_app/pemasangan-bota/'
      path: '/pemasangan-bota'
      fullPath: '/pemasangan-bota/'
      preLoaderRoute: typeof AppPemasanganBotaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orang-tua-asuh-saya/': {
      id: '/_app/orang-tua-asuh-saya/'
      path: '/orang-tua-asuh-saya'
      fullPath: '/orang-tua-asuh-saya/'
      preLoaderRoute: typeof AppOrangTuaAsuhSayaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manajemen-akun/': {
      id: '/_app/manajemen-akun/'
      path: '/manajemen-akun'
      fullPath: '/manajemen-akun/'
      preLoaderRoute: typeof AppManajemenAkunIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mahasiswa-asuh-saya/': {
      id: '/_app/mahasiswa-asuh-saya/'
      path: '/mahasiswa-asuh-saya'
      fullPath: '/mahasiswa-asuh-saya/'
      preLoaderRoute: typeof AppMahasiswaAsuhSayaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-hubungan-asuh/': {
      id: '/_app/data-hubungan-asuh/'
      path: '/data-hubungan-asuh'
      fullPath: '/data-hubungan-asuh/'
      preLoaderRoute: typeof AppDataHubunganAsuhIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daftar-transfer-mahasiswa/': {
      id: '/_app/daftar-transfer-mahasiswa/'
      path: '/daftar-transfer-mahasiswa'
      fullPath: '/daftar-transfer-mahasiswa/'
      preLoaderRoute: typeof AppDaftarTransferMahasiswaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daftar-terminasi/': {
      id: '/_app/daftar-terminasi/'
      path: '/daftar-terminasi'
      fullPath: '/daftar-terminasi/'
      preLoaderRoute: typeof AppDaftarTerminasiIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daftar-tagihan/': {
      id: '/_app/daftar-tagihan/'
      path: '/daftar-tagihan'
      fullPath: '/daftar-tagihan/'
      preLoaderRoute: typeof AppDaftarTagihanIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cari-mahasiswa/': {
      id: '/_app/cari-mahasiswa/'
      path: '/cari-mahasiswa'
      fullPath: '/cari-mahasiswa/'
      preLoaderRoute: typeof AppCariMahasiswaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$groupId': {
      id: '/_app/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AppGroupsGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daftar/terminasi-mahasiswa/': {
      id: '/_app/daftar/terminasi-mahasiswa/'
      path: '/daftar/terminasi-mahasiswa'
      fullPath: '/daftar/terminasi-mahasiswa/'
      preLoaderRoute: typeof AppDaftarTerminasiMahasiswaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/register/': {
      id: '/_app/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AppAuthRegisterIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/otp-verification/': {
      id: '/_app/auth/otp-verification/'
      path: '/auth/otp-verification'
      fullPath: '/auth/otp-verification/'
      preLoaderRoute: typeof AppAuthOtpVerificationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/lupa-password/': {
      id: '/_app/auth/lupa-password/'
      path: '/auth/lupa-password'
      fullPath: '/auth/lupa-password/'
      preLoaderRoute: typeof AppAuthLupaPasswordIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/login/': {
      id: '/_app/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AppAuthLoginIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/detail/mahasiswa/$detailId': {
      id: '/_app/detail/mahasiswa/$detailId'
      path: '/detail/mahasiswa/$detailId'
      fullPath: '/detail/mahasiswa/$detailId'
      preLoaderRoute: typeof AppDetailMahasiswaDetailIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/azure-key-vault/oauth2/callback/': {
      id: '/_app/integrations/azure-key-vault/oauth2/callback/'
      path: '/integrations/azure-key-vault/oauth2/callback'
      fullPath: '/integrations/azure-key-vault/oauth2/callback/'
      preLoaderRoute: typeof AppIntegrationsAzureKeyVaultOauth2CallbackIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppGroupsGroupIdRoute: typeof AppGroupsGroupIdRoute
  AppCariMahasiswaIndexRoute: typeof AppCariMahasiswaIndexRoute
  AppDaftarTagihanIndexRoute: typeof AppDaftarTagihanIndexRoute
  AppDaftarTerminasiIndexRoute: typeof AppDaftarTerminasiIndexRoute
  AppDaftarTransferMahasiswaIndexRoute: typeof AppDaftarTransferMahasiswaIndexRoute
  AppDataHubunganAsuhIndexRoute: typeof AppDataHubunganAsuhIndexRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
  AppMahasiswaAsuhSayaIndexRoute: typeof AppMahasiswaAsuhSayaIndexRoute
  AppManajemenAkunIndexRoute: typeof AppManajemenAkunIndexRoute
  AppOrangTuaAsuhSayaIndexRoute: typeof AppOrangTuaAsuhSayaIndexRoute
  AppPemasanganBotaIndexRoute: typeof AppPemasanganBotaIndexRoute
  AppPendaftaranIndexRoute: typeof AppPendaftaranIndexRoute
  AppPersetujuanAsuhIndexRoute: typeof AppPersetujuanAsuhIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppStatusTransaksiIndexRoute: typeof AppStatusTransaksiIndexRoute
  AppVerifikasiAkunIndexRoute: typeof AppVerifikasiAkunIndexRoute
  AppDetailMahasiswaDetailIdRoute: typeof AppDetailMahasiswaDetailIdRoute
  AppAuthLoginIndexRoute: typeof AppAuthLoginIndexRoute
  AppAuthLupaPasswordIndexRoute: typeof AppAuthLupaPasswordIndexRoute
  AppAuthOtpVerificationIndexRoute: typeof AppAuthOtpVerificationIndexRoute
  AppAuthRegisterIndexRoute: typeof AppAuthRegisterIndexRoute
  AppDaftarTerminasiMahasiswaIndexRoute: typeof AppDaftarTerminasiMahasiswaIndexRoute
  AppIntegrationsAzureKeyVaultOauth2CallbackIndexRoute: typeof AppIntegrationsAzureKeyVaultOauth2CallbackIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppGroupsGroupIdRoute: AppGroupsGroupIdRoute,
  AppCariMahasiswaIndexRoute: AppCariMahasiswaIndexRoute,
  AppDaftarTagihanIndexRoute: AppDaftarTagihanIndexRoute,
  AppDaftarTerminasiIndexRoute: AppDaftarTerminasiIndexRoute,
  AppDaftarTransferMahasiswaIndexRoute: AppDaftarTransferMahasiswaIndexRoute,
  AppDataHubunganAsuhIndexRoute: AppDataHubunganAsuhIndexRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
  AppMahasiswaAsuhSayaIndexRoute: AppMahasiswaAsuhSayaIndexRoute,
  AppManajemenAkunIndexRoute: AppManajemenAkunIndexRoute,
  AppOrangTuaAsuhSayaIndexRoute: AppOrangTuaAsuhSayaIndexRoute,
  AppPemasanganBotaIndexRoute: AppPemasanganBotaIndexRoute,
  AppPendaftaranIndexRoute: AppPendaftaranIndexRoute,
  AppPersetujuanAsuhIndexRoute: AppPersetujuanAsuhIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppStatusTransaksiIndexRoute: AppStatusTransaksiIndexRoute,
  AppVerifikasiAkunIndexRoute: AppVerifikasiAkunIndexRoute,
  AppDetailMahasiswaDetailIdRoute: AppDetailMahasiswaDetailIdRoute,
  AppAuthLoginIndexRoute: AppAuthLoginIndexRoute,
  AppAuthLupaPasswordIndexRoute: AppAuthLupaPasswordIndexRoute,
  AppAuthOtpVerificationIndexRoute: AppAuthOtpVerificationIndexRoute,
  AppAuthRegisterIndexRoute: AppAuthRegisterIndexRoute,
  AppDaftarTerminasiMahasiswaIndexRoute: AppDaftarTerminasiMahasiswaIndexRoute,
  AppIntegrationsAzureKeyVaultOauth2CallbackIndexRoute:
    AppIntegrationsAzureKeyVaultOauth2CallbackIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
