export const mahasiswaColumns = {
    id: "ID Akun",
    email: "Email",
    type: "Tipe",
    phoneNumber: "No. Telp",
    provider: "Provider",
    name: "Nama",
    nim: "NIM",
    mahasiswaStatus: "Status Mahasiswa",
    description: "Essay",
    file: "Berkas Pengajuan Pendaftaran",
    major: "Jurusan",
    faculty: "Fakultas",
    cityOfOrigin: "Asal Daerah",
    highschoolAlumni: "Asal Sekolah",
    religion: "Agama",
    gender: "Jenis Kelamin",
    gpa: "IPK",
    kk: "Berkas Kartu Keluarga",
    ktm: "Berkas KTM",
    waliRecommendationLetter: "Berkas Rekomendasi Wali",
    transcript: "Berkas Transkrip Nilai",
    salaryReport: "Berkas Slip Gaji",
    pbb: "Berkas PBB",
    electricityBill: "Berkas Tagihan Listrik",
    ditmawaRecommendationLetter: "Berkas Rekomendasi Ditmawa",
    notes: "Catatan Mahasiswa",
    adminOnlyNotes: "Catatan Admin",
  };
  
  export const otaColumns = {
    id: "ID Akun",
    email: "Email",
    type: "Tipe",
    phoneNumber: "No. Telp",
    provider: "Provider",
    name: "Nama",
    job: "Pekerjaan",
    address: "Alamat",
    linkage: "Keterkaitan dengan ITB",
    funds: "Dana Asuh per Mahasiswa",
    maxCapacity: "Jumlah Mahasiswa Maksimal",
    startDate: "Tanggal Mulai Pemberian Dana",
    maxSemester: "Jangka Waktu Pemberian Dana",
    transferDate: "Tanggal Transfer Dana",
    criteria: "Kriteria",
    allowedAdminSelection: "Bersedia Dipilihkan oleh Admin",
  };
  
  export const linkColumns = [
    "file",
    "kk",
    "ktm",
    "waliRecommendationLetter",
    "transcript",
    "salaryReport",
    "pbb",
    "electricityBill",
    "ditmawaRecommendationLetter",
  ];