import { PrismaClient } from "../../generated/prisma";
import bcrypt from "bcryptjs";

export async function seedOtaProfiles(prisma: PrismaClient) {
  console.log("Seeding OTA profiles...");

  const defaultPassword = await bcrypt.hash("Password123!", 10);

  const otaData = [
    {
      email: "ota1@example.com",
      phoneNumber: "628111222333",
      name: "OTA Donor Satu",
      job: "Dosen Teknik ITB",
      address: "Jl. Ganesha No. 10, Bandung",
      linkage: "dosen" as const,
      funds: 500000,
      maxCapacity: 3,
      startDate: new Date("2024-01-01"),
      maxSemester: 8,
      transferDate: 5,
      criteria: "Mahasiswa aktif dengan IPK min 3.0, perlu bantuan finansial",
      isDetailVisible: true,
      allowAdminSelection: false,
    },
    {
      email: "ota2@example.com",
      phoneNumber: "628444555666",
      name: "OTA Donor Dua",
      job: "Alumni ITB – Software Engineer",
      address: "Jl. Pasteur No. 25, Bandung",
      linkage: "alumni" as const,
      funds: 750000,
      maxCapacity: 2,
      startDate: new Date("2024-02-01"),
      maxSemester: 6,
      transferDate: 10,
      criteria: "Preferensi mahasiswa jurusan teknik, berasal dari luar Jawa",
      isDetailVisible: true,
      allowAdminSelection: true,
    },
    {
      email: "ota3@example.com",
      phoneNumber: "628111000003",
      name: "OTA Donor Tiga",
      job: "Pengusaha",
      address: "Jl. Dago No. 50, Bandung",
      linkage: "lainnya" as const,
      funds: 1000000,
      maxCapacity: 5,
      startDate: new Date("2024-01-15"),
      maxSemester: 8,
      transferDate: 1,
      criteria: "Terbuka untuk semua jurusan, utamakan yang IPK bagus",
      isDetailVisible: false,
      allowAdminSelection: true,
    },
    {
      email: "ota4@example.com",
      phoneNumber: "628444000004",
      name: "OTA Donor Empat",
      job: "OTM ITB",
      address: "Jl. Tamansari No. 64, Bandung",
      linkage: "otm" as const,
      funds: 600000,
      maxCapacity: 3,
      startDate: new Date("2024-03-01"),
      maxSemester: 8,
      transferDate: 15,
      criteria: "Mahasiswa yang membutuhkan dukungan finansial dari keluarga kurang mampu",
      isDetailVisible: true,
      allowAdminSelection: false,
    },
    {
      email: "ota5@example.com",
      phoneNumber: "628111000005",
      name: "OTA Donor Lima",
      job: "Alumni ITB – Dokter",
      address: "Jl. Buah Batu No. 100, Bandung",
      linkage: "alumni" as const,
      funds: 800000,
      maxCapacity: 2,
      startDate: new Date("2024-04-01"),
      maxSemester: 10,
      transferDate: 7,
      criteria: "Preferensi jurusan FMIPA atau SF, IPK min 3.2",
      isDetailVisible: true,
      allowAdminSelection: false,
    },
    {
      email: "ota6@example.com",
      phoneNumber: "628444000006",
      name: "OTA Donor Enam",
      job: "Manajer Perusahaan",
      address: "Jl. Setiabudhi No. 77, Bandung",
      linkage: "lainnya" as const,
      funds: 500000,
      maxCapacity: 4,
      startDate: new Date("2024-01-01"),
      maxSemester: 8,
      transferDate: 20,
      criteria: "Terbuka semua jurusan",
      isDetailVisible: false,
      allowAdminSelection: true,
    },
    {
      email: "ota7@example.com",
      phoneNumber: "628111000007",
      name: "OTA Donor Tujuh",
      job: "Dosen FMIPA ITB",
      address: "Jl. Ganesha No. 15, Bandung",
      linkage: "dosen" as const,
      funds: 700000,
      maxCapacity: 2,
      startDate: new Date("2024-02-15"),
      maxSemester: 8,
      transferDate: 3,
      criteria: "Mahasiswa FMIPA atau SITH, berasal dari daerah terpencil",
      isDetailVisible: true,
      allowAdminSelection: false,
    },
    {
      email: "ota8@example.com",
      phoneNumber: "628444000008",
      name: "OTA Donor Delapan",
      job: "Alumni ITB – Insinyur",
      address: "Jl. Dipatiukur No. 35, Bandung",
      linkage: "alumni" as const,
      funds: 900000,
      maxCapacity: 3,
      startDate: new Date("2024-03-15"),
      maxSemester: 8,
      transferDate: 12,
      criteria: "Jurusan teknik sipil atau teknik lingkungan",
      isDetailVisible: true,
      allowAdminSelection: true,
    },
    {
      email: "ota9@example.com",
      phoneNumber: "628444000009",
      name: "OTA Donor Sembilan",
      job: "Wirausahawan",
      address: "Jl. Cihampelas No. 200, Bandung",
      linkage: "lainnya" as const,
      funds: 650000,
      maxCapacity: 4,
      startDate: new Date("2024-05-01"),
      maxSemester: 6,
      transferDate: 25,
      criteria: "IPK min 2.75, aktif berorganisasi",
      isDetailVisible: false,
      allowAdminSelection: true,
    },
    {
      email: "ota10@example.com",
      phoneNumber: "628444000010",
      name: "OTA Donor Sepuluh",
      job: "Direktur BUMN",
      address: "Jl. Asia Afrika No. 5, Bandung",
      linkage: "lainnya" as const,
      funds: 1500000,
      maxCapacity: 5,
      startDate: new Date("2024-01-01"),
      maxSemester: 10,
      transferDate: 1,
      criteria: "Mahasiswa berprestasi dari keluarga kurang mampu",
      isDetailVisible: true,
      allowAdminSelection: false,
    },
    {
      email: "ota11@example.com",
      phoneNumber: "628444000011",
      name: "OTA Donor Sebelas",
      job: "Alumni ITB – Peneliti",
      address: "Jl. Ciumbuleuit No. 80, Bandung",
      linkage: "alumni" as const,
      funds: 550000,
      maxCapacity: 2,
      startDate: new Date("2024-06-01"),
      maxSemester: 8,
      transferDate: 8,
      criteria: "Mahasiswa yang memiliki minat riset",
      isDetailVisible: true,
      allowAdminSelection: false,
    },
    {
      email: "ota12@example.com",
      phoneNumber: "628444000012",
      name: "OTA Donor Dua Belas",
      job: "Guru Besar ITB",
      address: "Jl. Ganesha No. 20, Bandung",
      linkage: "dosen" as const,
      funds: 800000,
      maxCapacity: 3,
      startDate: new Date("2024-02-01"),
      maxSemester: 8,
      transferDate: 5,
      criteria: "Mahasiswa S1 dengan IPK di atas 3.5",
      isDetailVisible: true,
      allowAdminSelection: true,
    },
    {
      email: "ota13@example.com",
      phoneNumber: "628444000013",
      name: "OTA Donor Tiga Belas",
      job: "Pengacara",
      address: "Jl. Riau No. 45, Bandung",
      linkage: "lainnya" as const,
      funds: 600000,
      maxCapacity: 2,
      startDate: new Date("2024-04-15"),
      maxSemester: 8,
      transferDate: 18,
      criteria: "Tidak ada kriteria khusus",
      isDetailVisible: false,
      allowAdminSelection: true,
    },
    {
      email: "ota14@example.com",
      phoneNumber: "628444000014",
      name: "OTA Donor Empat Belas",
      job: "Alumni ITB – Arsitek",
      address: "Jl. Braga No. 30, Bandung",
      linkage: "alumni" as const,
      funds: 700000,
      maxCapacity: 2,
      startDate: new Date("2024-03-01"),
      maxSemester: 8,
      transferDate: 10,
      criteria: "Preferensi jurusan arsitektur atau desain",
      isDetailVisible: true,
      allowAdminSelection: false,
    },
    {
      email: "ota15@example.com",
      phoneNumber: "628444000015",
      name: "OTA Donor Lima Belas",
      job: "OTM ITB",
      address: "Jl. Tamansari No. 70, Bandung",
      linkage: "otm" as const,
      funds: 500000,
      maxCapacity: 4,
      startDate: new Date("2024-01-01"),
      maxSemester: 8,
      transferDate: 15,
      criteria: "Mahasiswa dari keluarga tidak mampu",
      isDetailVisible: true,
      allowAdminSelection: true,
    },
  ];

  for (const ota of otaData) {
    await prisma.user.upsert({
      where: { email: ota.email },
      update: {},
      create: {
        email: ota.email,
        phoneNumber: ota.phoneNumber,
        password: defaultPassword,
        name: ota.name,
        role: "OrangTuaAsuh",
        verificationStatus: "verified",
        applicationStatus: "accepted",
        OtaProfile: {
          create: {
            name: ota.name,
            job: ota.job,
            address: ota.address,
            linkage: ota.linkage,
            funds: ota.funds,
            maxCapacity: ota.maxCapacity,
            startDate: ota.startDate,
            maxSemester: ota.maxSemester,
            transferDate: ota.transferDate,
            criteria: ota.criteria,
            isDetailVisible: ota.isDetailVisible,
            allowAdminSelection: ota.allowAdminSelection,
          },
        },
      },
    });
  }

  console.log("✅ OTA profiles seeded (15 donors)");
}
