import { PrismaClient } from "../../generated/prisma";
import bcrypt from "bcryptjs";

// NIM prefix 3 digit → { fakultas, jurusan }
// Dipakai untuk generate NIM mahasiswa seed
export const nimPrefixMap: Record<
  string,
  { faculty: string; major: string; nim_prefix: string }
> = {
  "135": { faculty: "STEI_K", major: "Teknik_Informatika", nim_prefix: "135" },
  "132": { faculty: "STEI_R", major: "Teknik_Elektro", nim_prefix: "132" },
  "131": { faculty: "FTMD", major: "Teknik_Mesin", nim_prefix: "131" },
  "150": { faculty: "FTI", major: "Teknik_Industri", nim_prefix: "150" },
  "130": { faculty: "FTI", major: "Teknik_Kimia", nim_prefix: "130" },
  "151": { faculty: "FTSL", major: "Teknik_Sipil", nim_prefix: "151" },
  "120": { faculty: "FITB", major: "Teknik_Geologi", nim_prefix: "120" },
  "101": { faculty: "FMIPA", major: "Matematika", nim_prefix: "101" },
};

export async function seedUsers(prisma: PrismaClient) {
  console.log("Seeding users...");

  const defaultPassword = await bcrypt.hash("Password123!", 10);
  const adminPassword = await bcrypt.hash("Admin123!", 10);

  // ── Admin ──────────────────────────────────────────────────────────────────
  await prisma.user.upsert({
    where: { email: "admin@example.com" },
    update: {},
    create: {
      email: "admin@example.com",
      password: adminPassword,
      name: "Admin",
      role: "Admin",
      verificationStatus: "verified",
      applicationStatus: "accepted",
      AdminProfile: { create: { name: "Admin" } },
    },
  });

  // ── Bankes staff (koordinator Bankes di sistem OTA) ────────────────────────
  for (let i = 1; i <= 2; i++) {
    await prisma.user.upsert({
      where: { email: `bankes${i}@example.com` },
      update: {},
      create: {
        email: `bankes${i}@example.com`,
        phoneNumber: `62812186548${i}`,
        password: defaultPassword,
        name: `Bankes ${i}`,
        role: "Bankes",
        verificationStatus: "verified",
        applicationStatus: "accepted",
      },
    });
  }

  // ── Pengurus IOM ───────────────────────────────────────────────────────────
  for (let i = 1; i <= 4; i++) {
    await prisma.user.upsert({
      where: { email: `pengurus${i}@example.com` },
      update: {},
      create: {
        email: `pengurus${i}@example.com`,
        phoneNumber: `62812758624${i}`,
        password: defaultPassword,
        name: `Pengurus IOM ${i}`,
        role: "Pengurus_IOM",
        verificationStatus: "verified",
        applicationStatus: "accepted",
      },
    });
  }

  // ── Pewawancara (Bankes only) ───────────────────────────────────────────────
  for (let i = 1; i <= 3; i++) {
    await prisma.user.upsert({
      where: { email: `pewawancara${i}@example.com` },
      update: {},
      create: {
        email: `pewawancara${i}@example.com`,
        password: defaultPassword,
        name: `Pewawancara ${i}`,
        role: "Pewawancara",
        verificationStatus: "verified",
        applicationStatus: "accepted",
      },
    });
  }

  // ── Mahasiswa ──────────────────────────────────────────────────────────────
  // Data diambil dari OTA seed yang existing (18 mahasiswa dengan NIM asli ITB)
  const mahasiswaData = [
    {
      email: "13599101@mahasiswa.itb.ac.id",
      nim: "13599101",
      name: "Mahasiswa One",
      phoneNumber: "628123456780",
      applicationStatus: "accepted" as const,
      faculty: "STEI_K" as const,
      major: "Teknik_Informatika" as const,
      cityOfOrigin: "Jakarta",
      highschoolAlumni: "SMA Negeri 1 Jakarta",
      religion: "Islam",
      gender: "M",
      gpa: 3.8,
      bill: 500000,
      mahasiswaStatus: "active" as const,
    },
    {
      email: "13299102@mahasiswa.itb.ac.id",
      nim: "13299102",
      name: "Mahasiswa Two",
      phoneNumber: "628198765432",
      applicationStatus: "accepted" as const,
      faculty: "STEI_R" as const,
      major: "Teknik_Elektro" as const,
      cityOfOrigin: "Bandung",
      highschoolAlumni: "SMA Negeri 3 Bandung",
      religion: "Islam",
      gender: "F",
      gpa: 3.5,
      bill: 600000,
      mahasiswaStatus: "active" as const,
    },
    {
      email: "13199103@mahasiswa.itb.ac.id",
      nim: "13199103",
      name: "Mahasiswa Three",
      phoneNumber: "628198702490",
      applicationStatus: "accepted" as const,
      faculty: "FTMD" as const,
      major: "Teknik_Mesin" as const,
      cityOfOrigin: "Surabaya",
      highschoolAlumni: "SMA Negeri 5 Surabaya",
      religion: "Kristen Protestan",
      gender: "M",
      gpa: 3.2,
      bill: 700000,
      mahasiswaStatus: "active" as const,
    },
    {
      email: "15099104@mahasiswa.itb.ac.id",
      nim: "15099104",
      name: "Mahasiswa Four",
      phoneNumber: "628198766782",
      applicationStatus: "pending" as const,
      faculty: "FTI" as const,
      major: "Teknik_Industri" as const,
      cityOfOrigin: "Medan",
      highschoolAlumni: "SMA Swasta Harapan Medan",
      religion: "Islam",
      gender: "F",
      gpa: 3.0,
      bill: 550000,
      mahasiswaStatus: "inactive" as const,
    },
    {
      email: "13099105@mahasiswa.itb.ac.id",
      nim: "13099105",
      name: "Mahasiswa Five",
      phoneNumber: "628198987411",
      applicationStatus: "rejected" as const,
      faculty: "FTI" as const,
      major: "Teknik_Kimia" as const,
      cityOfOrigin: "Makassar",
      highschoolAlumni: "SMA Negeri 1 Makassar",
      religion: "Islam",
      gender: "M",
      gpa: 2.8,
      bill: 0,
      mahasiswaStatus: "inactive" as const,
    },
    {
      email: "15199106@mahasiswa.itb.ac.id",
      nim: "15199106",
      name: "Mahasiswa Six",
      phoneNumber: "628100000006",
      applicationStatus: "accepted" as const,
      faculty: "FTSL" as const,
      major: "Teknik_Sipil" as const,
      cityOfOrigin: "Yogyakarta",
      highschoolAlumni: "SMA Negeri 1 Yogyakarta",
      religion: "Islam",
      gender: "M",
      gpa: 3.6,
      bill: 450000,
      mahasiswaStatus: "active" as const,
    },
    {
      email: "12099107@mahasiswa.itb.ac.id",
      nim: "12099107",
      name: "Mahasiswa Seven",
      phoneNumber: "628100000007",
      applicationStatus: "accepted" as const,
      faculty: "FITB" as const,
      major: "Teknik_Geologi" as const,
      cityOfOrigin: "Semarang",
      highschoolAlumni: "SMA Negeri 3 Semarang",
      religion: "Katolik",
      gender: "F",
      gpa: 3.4,
      bill: 480000,
      mahasiswaStatus: "active" as const,
    },
    {
      email: "15499108@mahasiswa.itb.ac.id",
      nim: "15499108",
      name: "Mahasiswa Eight",
      phoneNumber: "628100000008",
      applicationStatus: "accepted" as const,
      faculty: "FTSL" as const,
      major: "Teknik_Lingkungan" as const,
      cityOfOrigin: "Palembang",
      highschoolAlumni: "SMA Negeri 2 Palembang",
      religion: "Islam",
      gender: "M",
      gpa: 3.3,
      bill: 520000,
      mahasiswaStatus: "active" as const,
    },
    {
      email: "15099109@mahasiswa.itb.ac.id",
      nim: "15099109",
      name: "Mahasiswa Nine",
      phoneNumber: "628100000009",
      applicationStatus: "pending" as const,
      faculty: "FTI" as const,
      major: "Teknik_Industri" as const,
      cityOfOrigin: "Balikpapan",
      highschoolAlumni: "SMA Negeri 1 Balikpapan",
      religion: "Islam",
      gender: "F",
      gpa: 3.1,
      bill: 0,
      mahasiswaStatus: "inactive" as const,
    },
    {
      email: "15499110@mahasiswa.itb.ac.id",
      nim: "15499110",
      name: "Mahasiswa Ten",
      phoneNumber: "628100000010",
      applicationStatus: "pending" as const,
      faculty: "FTSL" as const,
      major: "Teknik_Lingkungan" as const,
      cityOfOrigin: "Pontianak",
      highschoolAlumni: "SMA Negeri 1 Pontianak",
      religion: "Buddha",
      gender: "M",
      gpa: 3.0,
      bill: 0,
      mahasiswaStatus: "inactive" as const,
    },
    {
      email: "13499111@mahasiswa.itb.ac.id",
      nim: "13499111",
      name: "Mahasiswa Eleven",
      phoneNumber: "628100000011",
      applicationStatus: "rejected" as const,
      faculty: "FTMD" as const,
      major: "Aeronotika_dan_Astronotika" as const,
      cityOfOrigin: "Manado",
      highschoolAlumni: "SMA Negeri 1 Manado",
      religion: "Kristen Protestan",
      gender: "F",
      gpa: 2.9,
      bill: 0,
      mahasiswaStatus: "inactive" as const,
    },
    {
      email: "13199112@mahasiswa.itb.ac.id",
      nim: "13199112",
      name: "Mahasiswa Twelve",
      phoneNumber: "628100000012",
      applicationStatus: "accepted" as const,
      faculty: "FTMD" as const,
      major: "Teknik_Mesin" as const,
      cityOfOrigin: "Pekanbaru",
      highschoolAlumni: "SMA Negeri 2 Pekanbaru",
      religion: "Islam",
      gender: "M",
      gpa: 3.7,
      bill: 600000,
      mahasiswaStatus: "active" as const,
    },
    {
      email: "13099113@mahasiswa.itb.ac.id",
      nim: "13099113",
      name: "Mahasiswa Thirteen",
      phoneNumber: "628100000013",
      applicationStatus: "accepted" as const,
      faculty: "FTI" as const,
      major: "Teknik_Kimia" as const,
      cityOfOrigin: "Cirebon",
      highschoolAlumni: "SMA Negeri 1 Cirebon",
      religion: "Islam",
      gender: "F",
      gpa: 3.5,
      bill: 550000,
      mahasiswaStatus: "active" as const,
    },
    {
      email: "10199114@mahasiswa.itb.ac.id",
      nim: "10199114",
      name: "Mahasiswa Fourteen",
      phoneNumber: "628100000014",
      applicationStatus: "accepted" as const,
      faculty: "FMIPA" as const,
      major: "Matematika" as const,
      cityOfOrigin: "Solo",
      highschoolAlumni: "SMA Negeri 1 Solo",
      religion: "Islam",
      gender: "M",
      gpa: 3.9,
      bill: 650000,
      mahasiswaStatus: "active" as const,
    },
    {
      email: "15299115@mahasiswa.itb.ac.id",
      nim: "15299115",
      name: "Mahasiswa Fifteen",
      phoneNumber: "628100000015",
      applicationStatus: "accepted" as const,
      faculty: "FTSL" as const,
      major: "Teknik_Sipil" as const,
      cityOfOrigin: "Bogor",
      highschoolAlumni: "SMA Negeri 1 Bogor",
      religion: "Islam",
      gender: "F",
      gpa: 3.4,
      bill: 480000,
      mahasiswaStatus: "active" as const,
    },
    {
      email: "19099116@mahasiswa.itb.ac.id",
      nim: "19099116",
      name: "Mahasiswa Sixteen",
      phoneNumber: "628100000016",
      applicationStatus: "pending" as const,
      faculty: "SBM" as const,
      major: "Manajemen" as const,
      cityOfOrigin: "Depok",
      highschoolAlumni: "SMA Negeri 1 Depok",
      religion: "Islam",
      gender: "M",
      gpa: 3.2,
      bill: 0,
      mahasiswaStatus: "inactive" as const,
    },
    {
      email: "10399117@mahasiswa.itb.ac.id",
      nim: "10399117",
      name: "Mahasiswa Seventeen",
      phoneNumber: "628100000017",
      applicationStatus: "accepted" as const,
      faculty: "FMIPA" as const,
      major: "Kimia" as const,
      cityOfOrigin: "Bekasi",
      highschoolAlumni: "SMA Negeri 2 Bekasi",
      religion: "Islam",
      gender: "F",
      gpa: 3.6,
      bill: 500000,
      mahasiswaStatus: "active" as const,
    },
    {
      email: "13599118@mahasiswa.itb.ac.id",
      nim: "13599118",
      name: "Mahasiswa Eighteen",
      phoneNumber: "628100000018",
      applicationStatus: "accepted" as const,
      faculty: "STEI_K" as const,
      major: "Sistem_Teknologi_dan_Informasi" as const,
      cityOfOrigin: "Tangerang",
      highschoolAlumni: "SMA Negeri 1 Tangerang",
      religion: "Islam",
      gender: "M",
      gpa: 3.7,
      bill: 570000,
      mahasiswaStatus: "active" as const,
    },
  ];

  const dueDateTime = new Date();
  dueDateTime.setMonth(dueDateTime.getMonth() + 6);

  for (const m of mahasiswaData) {
    await prisma.user.upsert({
      where: { email: m.email },
      update: {},
      create: {
        email: m.email,
        phoneNumber: m.phoneNumber,
        password: defaultPassword,
        name: m.name,
        role: "Mahasiswa",
        verificationStatus: "verified",
        applicationStatus: m.applicationStatus,
        MahasiswaProfile: {
          create: {
            nim: m.nim,
            name: m.name,
            faculty: m.faculty as any,
            major: m.major as any,
            cityOfOrigin: m.cityOfOrigin,
            highschoolAlumni: m.highschoolAlumni,
            religion: m.religion,
            gender: m.gender,
            gpa: m.gpa,
            bill: m.bill,
            mahasiswaStatus: m.mahasiswaStatus,
            dueNextUpdateAt: dueDateTime,
          },
        },
      },
    });
  }

  console.log("✅ Users seeded (admin, bankes, pengurus, pewawancara, mahasiswa)");
  return mahasiswaData.map((m) => m.email);
}
